### ISSUE TITLE
Windows "unzip" command does not exist

### ISSUE THREAD

**Issue by sjhill01** [newbit1/rootAVD#1]
On my first run through, trying to execute the batch file failed because the "unzip" command isn't native to Windows 10. If you want to make a requirement of Windows 10 build 17063 or later, you can use:

    	md %ROOTAVD%\Magisk
	tar -xf magisk.zip --directory %ROOTAVD%\Magisk

Otherwise you should add a requirement for getting some kind of "unzip" command first. I didn't submit this as a change b/c it will depend on your desire for how to handle prerequisites.

**Comment by newbit1** [comment]
Thanks for your feedback, very much appreciated.
I thought there is a built in stock zip program in Windows 10?
Weird, are you certain tar is standard build in Windows 10?

**Comment by sjhill01** [comment]
Yep: https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409

I found out by following along on this discussion: https://superuser.com/questions/1314420/how-to-unzip-a-file-using-the-cmd
