### ISSUE TITLE
APPLE SILICON(M1) MONTEREY ROOT ERROR

### ISSUE THREAD

**Issue by secfb** [newbit1/rootAVD#13]
**OS: macOS Monterey 12.0.1 arm64**
 **CPU: Apple M1**

When I run the program, I get the following error. Even though I tried version 30 and 31, I get the same error. How can I solve this problem?
After downloading the apk version of Magisk from its site, should I install it in the APP folder?
https://magiskmanager.com/downloading-magisk-manager/

Can you help with this?

![1](https://user-images.githubusercontent.com/38748801/140607280-ffb21684-1917-4635-90d0-0d3709512c28.png)

**USAGE COMMAND**

```ruby 
sudo bash rootAVD.sh /Users/cmd/Library/Android/sdk/system-images/android-30/google_apis/arm64-v8a/ramdisk.img 
```

```ruby 
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[-] Magisk installer Zip exists already
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 225.3 MB/s (6874374 bytes in 0.029s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/cmd/Library/Android/sdk/system-images/android-30/google_apis/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 300.9 MB/s (1557267 bytes in 0.005s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 220.1 MB/s (7826127 bytes in 0.034s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in an emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 30
[-] First API Level: 30
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[*] Extracting busybox from script ...
[!] Found a working busybox Binary:
[!] BusyBox v1.33.1-Magisk (2021-05-08 15:20:41 PDT) multi-call binary.
[-] Checking AVDs Internet connection...
[!] AVD is offline
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[!] We are in an emulator shell
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '23.0' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[*] No 64-Bit Binarys found, please consider Magisk Alpha
[-] copy all armeabi-v7a files from /data/data/com.android.shell/Magisk/lib/armeabi-v7a to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses gzip compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[-] Multiple cpio archives detected
[*] Unpacking ramdisk ..
[-] Dumping from 0 to 1832688 ..
[-] Dumping from 1832704 to 4632124 ..
[*] Repacking ramdisk ..
[-] Deleting system ramdisk build.prop
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=2
[!] Boot image patched by unsupported programs
[!] Please restore back to stock boot image
[!] aborting the script
```

**Comment by newbit1** [comment]
You dont have to run the script as root. Just `./rootAVD.sh /Users/cmd/Library/Android/sdk/system-images/android-30/google_apis/arm64-v8a/ramdisk.img` is enough

64-Bit only systems are only supported by Magisk Canary and Alpha. The Stable release doesn't have
64-Bit Only features yet.
Make sure your AVD is only, then the script will give you the choice to download a different Magisk Version.

**Comment by secfb** [comment]
I have installed on API 30.I installed the stable version.  Error while installing other versions. But I could not install the burp certificate. What do you think I am doing wrong? Can you help with this?

![2](https://user-images.githubusercontent.com/38748801/140878007-868b6525-2430-48b3-9d0b-81438abb5a8e.png)
![1](https://user-images.githubusercontent.com/38748801/140877967-63de8302-c966-48fb-bf2b-4e4a35becdd7.png)
```ruby
emulator_arm64:/sdcard # id
uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
emulator_arm64:/sdcard # cp 9a5ba575.0 /system/etc/security/cacerts/
cp: /system/etc/security/cacerts//9a5ba575.0: Read-only file system
1|emulator_arm64:/sdcard # su cp 9a5ba575.0 /system/etc/security/cacerts/
emulator_arm64:/storage/emulated/0 # ls /system/etc/security/cacerts/9a5ba575.0
ls: /system/etc/security/cacerts/9a5ba575.0: No such file or directory
1|emulator_arm64:/storage/emulated/0 #
```
----------
I don't think I did root wrong.

<img width="382" alt="11" src="https://user-images.githubusercontent.com/38748801/140878306-c0309a1f-565c-452d-8fdd-793b2b2c12f6.png">

<img width="383" alt="22" src="https://user-images.githubusercontent.com/38748801/140878332-86127d4b-5fb9-4e30-8aa0-1ae54eb931d6.png">

**Comment by newbit1** [comment]
I don't know what a burp certificate is. But you have installed the canary version according to your screenshots.
So root worked nicely. If you are trying to copy or install any files to the system, it won't work that way.
You will need to create a Module for Magisk to do that. Check out the [Developer Guides](https://topjohnwu.github.io/Magisk/guides.html)
