### ISSUE TITLE
API 28

### ISSUE THREAD

**Issue by Jiang00** [newbit1/rootAVD#14]
Magisk patched boot image detected
[-] Constructing environment - PAY ATTENTION to the AVDs Screen
[!] not root yet
[!] Couldn't construct environment
[!] Double Check Root Access
[!] Re-Run Script with clean ramdisk.img and try again
[!] aborting the script

**Comment by newbit1** [comment]
[README.md](https://github.com/newbit1/rootAVD/blob/master/README.md) -> API 28 (Pie) is not supported at all -> [because](https://source.android.com/devices/bootloader/partitions/system-as-root#sar-partitioning)
