### ISSUE TITLE
ListAllAVDs doesnt work

### ISSUE THREAD

**Issue by 89z** [newbit1/rootAVD#15]
If I run this command:

~~~
rootAVD.bat ListAllAVDs
~~~

it just prints the help page

**Comment by newbit1** [comment]
did you run it in a powershell or cmd? the script is written for cmd.

**Comment by 89z** [comment]
I tried both, same result

**Comment by newbit1** [comment]
Then please more details.
Which system, how did you download the script?

**Comment by wangvic21** [comment]
I have the same problem.

- download with the git tool.
- system: Windows 21H

**Comment by wangvic21** [comment]
`set PATH=%LOCALAPPDATA%\Android\Sdk\platform-tools;%PATH%`

So, I think the env of ADB should in disk C: .
It works.
