### ISSUE TITLE
Magisk v23

### ISSUE THREAD

**Issue by 89z** [newbit1/rootAVD#16]
In this file:

https://github.com/newbit1/rootAVD/blob/master/rootAVD.sh

I see this line:

~~~
MAGISKZIPDL=https://github.com/topjohnwu/Magisk/releases/download/v22.0/Magisk-v22.0.apk
~~~

Can you change this to v23?

**Comment by newbit1** [comment]
No,
the magisk.zip is already v23.
You can choose a diffrent version during the script is running. If your avd is online.
