### ISSUE TITLE
Not working on latest android studio

### ISSUE THREAD

**Issue by hassanayoub1985** [newbit1/rootAVD#17]
the ramdisk successfully patched, the avd shitted down, and i power it on using cold boot now, then i tried root checker it shows not rooted, I tried :
./rootAVD.sh /Users/bixmatech/Library/Android/sdk/system-images/android-31/google_apis/x86_64/ramdisk.img  DEBUG PATCHFSTAB GetUSBHPmodZ
It shows this
{
Detected format: [lz4_legacy]
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=1
[-] Magisk patched boot image detected
[-] Constructing environment - PAY ATTENTION to the AVDs Screen
[!] not root yet
[!] Couldn't construct environment
[!] Double Check Root Access
[!] Re-Run Script with clean ramdisk.img and try again
[!] aborting the script
}

**Comment by newbit1** [comment]
The script is tested with the newest Android and AVD Versions.

Don't use the DEBUG command. It is for debugging only and doesn't copy the patched files back.
If the patch process worked and shut down the AVD, you must first open Magisk, it will finish
the root installation and reboots automatically. I don't know if root checker apps will detect this.
If you want to start all over, just run ./rootAVD.sh restore, and then you can begin again.

Android 31 (S) is a 64 Bit only System and needs  Magisk Canary or Alpha, as you can see in the [Compatibility Chart](https://github.com/newbit1/rootAVD#compatibility-chart)

**Comment by hassanayoub1985** [comment]
Yes , iI am using canary version, but the modules in it is not active. and when I try root checker it shows not root, however I can access from shell /data/data
how can I give a particular apk root access to test?

**Comment by newbit1** [comment]
I dont know.
Did you open Magisk?

**Comment by hassanayoub1985** [comment]
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 35.0 MB/s (7826127 bytes in 0.213s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in an emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x64 only
[-] Device SDK API: 31
[-] First API Level: 31
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[1] Local '23.0' (ENTER)
[2] Canary 92546e8a(23016)
[3] Stable 23.0
[4] Alpha 0c1f6881-alpha(23016)
[1] You choose Magisk Local Version '23.0'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[!] We are in an emulator shell
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '23.0' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[*] No 64-Bit Binarys found, please consider Magisk Alpha
[-] copy all x86 files from /data/data/com.android.shell/Magisk/lib/x86 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses lz4_legacy compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[*] After decompressing ramdisk.img, magiskboot will work
Detected format: [lz4_legacy]
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=1
[-] Magisk patched boot image detected
[-] Constructing environment - PAY ATTENTION to the AVDs Screen
[!] not root yet
[!] Couldn't construct environment
[!] Double Check Root Access
[!] Re-Run Script with clean ramdisk.img and try again
[!] aborting the script
![000](https://user-images.githubusercontent.com/26030596/146807794-a02f835e-b682-4189-8c41-7abcddf98db2.jpg)

**Comment by newbit1** [comment]
Restore your ramdisk and try it with the canary version.
[1] Local '23.0' (ENTER)
**[2] Canary 92546e8a(23016)**
[3] Stable 23.0
[4] Alpha 0c1f6881-alpha(23016)
[1] You choose Magisk Local Version '23.0'
rootAVD with Magisk '23.0' Installer
[-] Get Flags
[] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[] RECOVERYMODE=false
[-] KEEPVERITY=true
[] KEEPFORCEENCRYPT=true
**[] No 64-Bit Binarys found, please consider Magisk Alpha**

**Comment by hassanayoub1985** [comment]
I clicked on "2" when canary version appears, and when i cold boot the avd, it shows that canary is installed and asked for update, I updated magisk, and same issue.
Tested on android 12, api 32

**Comment by newbit1** [comment]
If you installed magisk canary, this is the up to date version.
It should only say, that some extra setup is needed and then reboot. Finish.
As i said, the script with the canary version is tested and working on the newest Studio and AVD. If you mixed up something in between, sometimes a wipe data helps, means starting with a fresh AVD installed version. Sorry for that inconvience.
