### ISSUE TITLE
Not Working on Api30 x86

### ISSUE THREAD

**Issue by djkcyl** [newbit1/rootAVD#18]
```
❯ .\rootAVD.bat C:\Users\cyl\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] ADB connectoin possible
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] looking for Magisk installer Zip
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] D:\下载\rootAVD-master\Magisk.zip: 1 file pushed, 0 skipped. 233.0 MB/s (6874374 bytes in 0.028s)
[*] create Backup File
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] C:\Users\cyl\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img: 1 file pushed, 0 skipped. 285.0 MB/s (1520108 bytes in 0.005s)
[-] Copy rootAVD Script into Magisk DIR
rootAVD.sh: 1 file pushed, 0 skipped. 126.4 MB/s (7826127 bytes in 0.059s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in an emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x86 only
[-] Device SDK API: 30
[-] First API Level: 30
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
unzip: couldn't open /data/data/com.android.shell/Magisk/Magisk.zip: I/O error
chmod: /data/data/com.android.shell/Magisk/lib: No such file or directory
[*] Extracting busybox from script ...
[!] There is no busybox behind the script
[*] Trying to Download the Up-To-Date Script Version
[!] Temporarily installing Magisk
cp: bad '/lib': No such file or directory
chmod: /data/data/com.android.shell/Magisk/lib: No such file or directory
[-] Checking AVDs Internet connection...
[!] AVD is offline
```
![image](https://user-images.githubusercontent.com/59153990/147467543-d1de2c8d-1663-4270-93ca-b91cbc8f0d08.png)
![image](https://user-images.githubusercontent.com/59153990/147467564-0a8343de-810e-4095-8897-1a2afac8fde1.png)
![image](https://user-images.githubusercontent.com/59153990/147467578-8c463f6c-349e-429e-bf8e-e7c80ce38811.png)

**Comment by newbit1** [comment]
unzip: couldn't open /data/data/com.android.shell/Magisk/Magisk.zip: I/O error

Something is wrong with your Magisk.zip

**Comment by djkcyl** [comment]
> unzip: couldn't open /data/data/com.android.shell/Magisk/Magisk.zip: I/O error
> 
> Something is wrong with your Magisk.zip

so, how to download it? [this url?](https://github.com/topjohnwu/Magisk/releases)

**Comment by newbit1** [comment]
Try to redownload the whole rootAVD package. If your AVD is online, it should offer you a downloas option as well.

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/147475933-508754d2-2a7b-4d31-863b-e82e2422ec67.png)
avd is indeed online

**Comment by djkcyl** [comment]
If I enter the install command, the installed magisk will be uninstalled

**Comment by djkcyl** [comment]
![image](https://user-images.githubusercontent.com/59153990/147476963-0953448e-69e5-42be-a114-baa8928817ae.png)
I re-downloaded rootAVD.zip

**Comment by djkcyl** [comment]
I found the reason, because I used the Chinese directory name
