### ISSUE TITLE
Syntax error in rootAVD.sh

### ISSUE THREAD

**Issue by sjhill01** [newbit1/rootAVD#2]
When I attempt to run the batch file on Windows (after fixing the unzip issue), I get the following error:

"[-] Pushing all the stuff into the ADB working DIR"
C:\Android\rootAVD\Magisk\: 20 files pushed, 0 skipped. 170.8 MB/s (11756017 bytes in 0.066s)
"[-] run the actual Boot/Ramdisk/Kernel Image Patch Script"
"[*] from Magisk by topjohnwu and modded by NewBit XDA"
**: not foundcom.android.shell/Magisk/rootAVD.sh[11]:
'data/data/com.android.shell/Magisk/rootAVD.sh[22]: syntax error: unexpected 'in**
"[-] After the ramdisk.img file is patched and back gz'ed,"

That line references the loop in getdir(). Removing that function temporarily uncovers a similar "syntax error" complaint for the "do" in installapps(). Removing that function temporarily runs into a problem with the "do" on line 265 of the original script (in InstallMagiskToAVD(), which I can't exactly remove to test further).

**Comment by sjhill01** [comment]
The issue is that the rootAVD.sh file has Windows line endings (at least it did on my system after a git clone). After opening and doing a "save as" in Textpad with Unix line endings, it worked properly!

**Comment by newbit1** [comment]
hmm, I did just download it from git and edited it with N++.
I will check the ending settings it. Perhaps this is the reason why shakalaca used this dos2unix command.
adb -e shell "dos2unix /data/local/tmp/process.sh"

**Comment by sjhill01** [comment]
Yeah, I found that note on his project README, too - I assume that's why. Not sure how dos2unix behaves if it's already unix, but might be worth incorporating it in the script?

**Comment by newbit1** [comment]
Yes absolutely! I just updated the rootAVD.sh with the unzipping into the emulator.
I will change the rootAVD.bat tonight.

**Comment by Wolfhound905** [comment]
I am getting this error
```[*] Set Directorys
[-] Test if ADB SHELL is working
[-] ADB connectoin possible
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] looking for Magisk installer Zip
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] B:\items\Projects\rootAVD\Magisk.zip: 1 file pushed, 0 skipped. 283.3 MB/s (11278270 bytes in 0.038s)
[-] Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] C:\Users\aiden\AppData\Local\Android\Sdk\system-images\android-31\google_apis\x86_64\ramdisk.img: 1 file pushed, 0 skipped. 301.4 MB/s (3685301 bytes in 0.012s)
[-] Copy rootAVD Script into Magisk DIR
rootAVD.sh: 1 file pushed, 0 skipped. 13.9 MB/s (78955 bytes in 0.005s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
: inaccessible or not foundl/Magisk/rootAVD.sh[7]:
: inaccessible or not foundl/Magisk/rootAVD.sh[11]:
'data/data/com.android.shell/Magisk/rootAVD.sh[14]: syntax error: unexpected 'in```
