### ISSUE TITLE
Error with Magisk - INSTALL_FAILED_VERIFICATION_FAILURE

### ISSUE THREAD

**Issue by b4cktr4ck2** [newbit1/rootAVD#20]
I have a specific use case wherein the system with the AVD is offline and cannot come online. I've tried running the script and it seems to work well until the end:

~rootAVD-master>.\rootAVD.bat \AppData\Local\Android\Sdk\system-images\android-30\google_apis_playstore\x86\ramdisk.img
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] ADB connectoin possible
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] looking for Magisk installer Zip
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-]\rootAVD-master\Magisk.zip: 1 file pushed, 0 skipped. 257.2 MB/s (6874374 bytes in 0.025s)
[*] create Backup File
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] \AppData\Local\Android\Sdk\system-images\android-30\google_apis_playstore\x86\ramdisk.img: 1 file pushed, 0 skipped. 323.0 MB/s (1300381 bytes in 0.004s)
[-] Copy rootAVD Script into Magisk DIR
rootAVD.sh: 1 file pushed, 0 skipped. 120.9 MB/s (7826127 bytes in 0.062s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in an emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x86 only
[-] Device SDK API: 30
[-] First API Level: 30
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is offline
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[!] We are in an emulator shell
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '23.0' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[-] copy all x86 files from /data/data/com.android.shell/Magisk/lib/x86 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses gzip compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[-] Multiple cpio archives detected
[*] Unpacking ramdisk ..
[-] Dumping from 0 to 1729528 ..
[-] Dumping from 1729536 to 3858348 ..
[*] Repacking ramdisk ..
[-] Deleting system ramdisk build.prop
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=0
[-] Stock boot image detected
[-] Patching ramdisk
[*] adding overlay.d/sbin folders to ramdisk
Loading cpio: [ramdisk.cpio]
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Dump cpio: [ramdisk.cpio]
[!] PATCHFSTAB=false
[!] Skipping fstab.ranchu patch with /dev/block/sda
[?] If you want fstab.ranchu patched, Call rootAVD with PATCHFSTAB
[!] AddRCscripts=false
[!] Skip adding *.rc scripts into ramdisk.img/sbin/*.rc
[?] If you want *.rc scripts added into ramdisk.img/sbin/*.rc, Call rootAVD with AddRCscripts
[!] patching the ramdisk with Magisk Init
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
[*] repacking back to ramdisk.img format
[!] Rename Magisk.zip to Magisk.apk
[*] Pull ramdiskpatched4AVD.img into ramdisk.img
[-] /data/data/com.android.shell/Magisk/ramdiskpatched4AVD.img: 1 file pulled, 0 skipped. 297.7 MB/s (1596324 bytes in 0.005s
[*] Pull Magisk.apk into
[-] /data/data/com.android.shell/Magisk/Magisk.apk: 1 file pulled, 0 skipped. 361.2 MB/s (6874374 bytes in 0.018s
[-] Clean up the ADB working space
[-] Install all APKs placed in the Apps folder
[*] Trying to install APPS\Magisk.apk
[-] adb: failed to install APPS\Magisk.apk: Failure [INSTALL_FAILED_VERIFICATION_FAILURE]
[-] Performing Streamed Install
[-] Shut-Down and Reboot [Cold Boot Now] the AVD and see if it worked
[-] Root and Su with Magisk for Android Studio AVDs
[-] Modded by NewBit XDA - Jan. 2021
[*] Huge Credits and big Thanks to topjohnwu, shakalaca and vvb2060
[-] Trying to shut down the AVD
[!] If the AVD doesnt shut down, try it manually!

Is there a way to get around this verification check offline?

**Comment by newbit1** [comment]
I can't reproduce this issue. It doesn't matter if I have the verify apps over USB Settings on or off, I can install the apk
without the INSTALL_FAILED_VERIFICATION_FAILURE error. You could try to manually drag and drop the magisk.apk
to your AVD.
Can you give me more of your settings specs so that I can reproduce this behavior?
Like how you switched to offline mode and if you changed anything related to the ADB connection within
the developer options.

**Comment by b4cktr4ck2** [comment]
Offline mode was switched to by disabling my host PC's network adapter, so from the AVD's perspective it just failed to establish a network connection. I can try to explicitly switch the phone offline and retry that way.

As an aside, I was able to work around the issue by disabling network connectivity for certain applications. This allowed for my use case to continue while keeping the device online and allow for Magisk to be installed and device to be rooted. 

Appreciate the assistance, and you can close the issue if you'd like as I consider it resolved.

**Comment by newbit1** [comment]
Thanks for the hints, but I can't get this issue. I've tried several machines and OS's, but the ADB Installation is not effected no matter how I disable Internet. If you find a way to reproduce the issue for me, I am happy to catch that error within the code.
