### ISSUE TITLE
InstallApps tries to install nothing since the Apps folder is empty.

### ISSUE THREAD

**Issue by StupidRepo** [newbit1/rootAVD#27]
Is there supposed to be any APKs in the apps directory?

**Comment by newbit1** [comment]
No.

**Comment by 89z** [comment]
I don't think the previous comment is correct, as videos I have seen show a file `Magisk.apk` in the `Apps` folder. It seems they are taking the file `Magisk.zip`, renaming it and moving it, but I am not sure.
