### ISSUE TITLE
Can't seem to make it work with BLUESTACKS

### ISSUE THREAD

**Issue by stephenjason89** [newbit1/rootAVD#28]
after doing ./rootAVD.sh BLUESTACKS
everything install successfully with some minor errors like
```
[-] Overwriting /boot/android/android/ramdisk.img with ramdiskpatched4AVD.img
cp: can't create '/boot/android/android/ramdisk.img': Read-only file system
[-] Change ramdisk Mode to 644
chmod: /boot/android/android/ramdisk.img: Read-only file system
[-] Change ramdisk Owner to System
chown: /boot/android/android/ramdisk.img: Read-only file system
```

I don't know how but after several tries it worked for me 1 time yesterday but i had to delete my bluestacks and redo the operation today. Can't seem to make it work and can't install Xposed either.

Any help is deeply appreciated

Thanks

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/3810177/164373049-a40148a0-e1f2-4903-9d60-414c4f8240eb.png">

**Comment by newbit1** [comment]
Oh, you had to delete it the whole bluestacks installation? I am sorry.
You should try to use the restore command first before you reinstall Bluestacks. I can't figure what stage you have now. Did root now work? And you stuck on a Module to install? Please provide a Link to your Module. Some newer Modules don't support Android 7 anymore, not even 8.
