### ISSUE TITLE
After I run the root command nothing happens

### ISSUE THREAD

**Issue by mthp1999** [newbit1/rootAVD#29]
![image](https://user-images.githubusercontent.com/12549239/166718826-d84c14ae-b6cc-48f8-85df-2fd72695be16.png)
After I try to run the root command it goes to the test adb shell return and then doesn't say anything after that, any ideas on how to fix?

**Comment by newbit1** [comment]
Oh thats a new one.
Can you connect via adb shell to the avd?
which terminal is it? Cmd?

**Comment by mthp1999** [comment]
I think so
![image](https://user-images.githubusercontent.com/12549239/166800249-16bafc72-c0c5-4730-bc51-218dc4b0991c.png)

**Comment by mthp1999** [comment]
Yeah just using windows terminal

**Comment by mthp1999** [comment]
Was able to shutdown the devices through shell

**Comment by newbit1** [comment]
Looks pretty good to me. And did it worked now?

**Comment by mthp1999** [comment]
It doesn't seem so, no magisk app is installed even on reboot. Doesnt look like it finishes the script based on your gif

**Comment by newbit1** [comment]
do you have a full log? As text and not just as screenshots.

**Comment by mthp1999** [comment]
where would the log save?

**Comment by newbit1** [comment]
Just copy  & paste the command window output

**Comment by sdlee3** [comment]
Same to me, after run the command , the emulator closed
./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/google_apis_playstore/arm64-v8a/ramdisk.img

I manually start the emulator again, then the emulator was stuck in a black screen forever, and did not proceed to startup the device. I check "adb devices" and "adb shell", it show the device is offline

![image](https://user-images.githubusercontent.com/9932670/175805250-08c7c2ce-7606-44c7-821a-eaa391b8d4de.png)

**Comment by newbit1** [comment]
> Same to me, after run the command , the emulator closed
> ./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/google_apis_playstore/arm64-v8a/ramdisk.img
> 
> I manually start the emulator again, then the emulator was stuck in a black screen forever, and did not proceed to startup the device. I check "adb devices" and "adb shell", it show the device is offline
> 
> ![image](https://user-images.githubusercontent.com/9932670/175805297-d5d7509e-2b66-4a31-8817-cbec30629bcc.png)
> 

Please provide the complete log

**Comment by wubaojie** [comment]
> 

i have encountered the similar problem, maybe you can try my approach.
first, use cmd shell to start the emulator, and the cmd is " ~/Library/Android/sdk/emulator/emulator -avd Pixel_2_API_30 -writable-system"
second, if the emulator runs ok, then you can try to launch emulator by android studio

**Comment by wubaojie** [comment]
> Same to me, after run the command , the emulator closed ./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/google_apis_playstore/arm64-v8a/ramdisk.img
> 
> I manually start the emulator again, then the emulator was stuck in a black screen forever, and did not proceed to startup the device. I check "adb devices" and "adb shell", it show the device is offline
> 
> ![image](https://user-images.githubusercontent.com/9932670/175805297-d5d7509e-2b66-4a31-8817-cbec30629bcc.png)



> Same to me, after run the command , the emulator closed ./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/google_apis_playstore/arm64-v8a/ramdisk.img
> 
> I manually start the emulator again, then the emulator was stuck in a black screen forever, and did not proceed to startup the device. I check "adb devices" and "adb shell", it show the device is offline
> 
> ![image](https://user-images.githubusercontent.com/9932670/175805297-d5d7509e-2b66-4a31-8817-cbec30629bcc.png)

i have encountered the similar problem, maybe you can try my approach.
first, use cmd shell to start the emulator, and the cmd is " ~/Library/Android/sdk/emulator/emulator -avd Pixel_2_API_30 -writable-system"
second, if the emulator runs ok, then you can try to launch emulator by android studio

> Same to me, after run the command , the emulator closed ./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/google_apis_playstore/arm64-v8a/ramdisk.img
> 
> I manually start the emulator again, then the emulator was stuck in a black screen forever, and did not proceed to startup the device. I check "adb devices" and "adb shell", it show the device is offline
> 
> ![image](https://user-images.githubusercontent.com/9932670/175805297-d5d7509e-2b66-4a31-8817-cbec30629bcc.png)

i have encountered the similar problem, maybe you can try my approach.
first, use cmd shell to start the emulator, and the cmd is " ~/Library/Android/sdk/emulator/emulator -avd Pixel_2_API_30 -writable-system"
second, if the emulator runs ok, then you can try to launch emulator by android studio

**Comment by smoothdvd** [comment]
Same here, M1 MacBook Air, android-30/google_apis_playstore/arm64-v8a/ramdisk.img

**Comment by ricklambrechts** [comment]
Same issue. I remove `@echo off` from the script for debugging and this is the output:

```

rootAVD-master>REM Set Folders and FileNames

rootAVD-master>echo [*] Set Directorys
[*] Set Directorys

rootAVD-master>set AVDPATHWITHRDFFILE=InstallApps

rootAVD-master>for /F "delims=" %i in ("InstallApps") do (
set AVDPATH=%~dpi
 set RDFFILE=%~nxi
)

rootAVD-master>(
set AVDPATH=rootAVD-master\
 set RDFFILE=InstallApps
)

rootAVD-master>REM If we can CD into the ramdisk.img, it is not a file!

rootAVD-master>cd InstallApps  1>nul 2>&1

rootAVD-master>if "1" == "0" (call :ShowHelpText )

rootAVD-master>if 1 == 0 (call :restore_backups )

rootAVD-master>call :TestADB

rootAVD-master>SetLocal EnableDelayedExpansion

rootAVD-master>set HOME=C:\Users\Rick Lambrechts\AppData\Local\

rootAVD-master>set ADB_DIR_W=Android\Sdk\platform-tools\

rootAVD-master>set ADB_DIR=""

rootAVD-master>set ADB_EX=""

rootAVD-master>echo [-] Test if ADB SHELL is working
[-] Test if ADB SHELL is working

rootAVD-master>set ADBWORKS=

rootAVD-master>adb shell -n echo true  1>tmpFile 2>&1

rootAVD-master>set /P ADBWORKS= 0<tmpFile

rootAVD-master>del tmpFile
rootAVD-master>                       ) else (
rootAVD-master>

```
