### ISSUE TITLE
How to enter safe mode when boot fails

### ISSUE THREAD

**Issue by andronoob** [newbit1/rootAVD#3]
Hmmm, in fact I have successfully entered safe mode (so that all magisk modules got disabled), by pressing volume down button.

However it seemed to be more tricky than expected. I tried pressing the volume down button since the emulator started, however sometimes it didn't enter safe mode. I then tried to repeat "releasing & immediately pressing down the button" every few seconds, it then seemed to work, however I still don't know the details.

**Comment by newbit1** [comment]
Is this really rootAVD related?

To disable [Magisk-Modules](https://topjohnwu.github.io/Magisk/guides.html#magisk-modules), you can place a disable file into its directory.

Or you can just delete them all at once like in the Magisk [FAQ](https://topjohnwu.github.io/Magisk/faq.html) mentioned.

You can do both via [adb](https://forum.xda-developers.com/t/guide-magisk-modules-disabler-for-modules-gone-wrong.3966867/page-5#post-83468771).

To boot your AVD into Safe Mode, you can follow the guide [How to boot your device up in android safe mode](https://gossipfunda.com/android-safe-mode-boot-turn-off/#How_to_boot_your_device_up_in_android_safe_mode)

Works perfect.

**Comment by andronoob** [comment]
>Is this really rootAVD related?

Yes, I think, without your amazing work I won't be able to install magisk onto AVD.

However I just want to share my experience.

>You can do both via adb.

When a problematic module blocks boot process, adb is simply not available at all.

>To boot your AVD into Safe Mode, you can follow the guide How to boot your device up in android safe mode

When the AVD simply fails to boot, there's no chance to click that "reboot to safe boot" button.

**Comment by andronoob** [comment]
I hope that some hints could be added to README and text prompt of this script, so that in the case a problematic module blocks the AVD from normally booting, the user will feel less anxious.

**Comment by newbit1** [comment]
What exactly do you want in the readme? The primary scope of the script is to install Magisk, everything beyond this is Magisk
related. You can always wipe data or restore the ramdisk.img

**Comment by andronoob** [comment]
>The primary scope of the script is to install Magisk, everything beyond this is Magisk
related.

Of course. However I didn't know Magisk supports safe mode in the beginning either. I think some reminders about this can be helpful.

Maybe just a reminder like "in case a problematic magisk module bricks your AVD, you may try press the volume down button to enter safe mode!" is enough.

>You can always wipe data or restore the ramdisk.img

Sometimes you don't want to wipe data. To my understanding, although restoring ramdisk.img can make the AVD boot again, it will neither disable any magisk module, nor provide root access, so that safe mode is still useful to quickly fix a "bricked" AVD by disabling all magisk modules.

**Comment by newbit1** [comment]
Agree! This does definitely elevate the support level, especially the part that avoids wiping the data.
Could you please provide me this "bricking" module? So I can reproduce that issue and a possible way to fix it.

**Comment by andronoob** [comment]
>Could you please provide me this "bricking" module? So I can reproduce that issue and a possible way to fix it.
Thanks, but, actually it was not a ZIP, I wanted to modify some system files, so I just copied the hosts module (inside `/data/adb/modules`) to achieve this. Other modules (including the hosts module) is working without problem.

**Comment by newbit1** [comment]
Then send me just this. Or create a module that breaks. Without something, I can't reproduce anything. Sorry

**Comment by andronoob** [comment]
>Or create a module that breaks.

Maybe you could try this (assuming you've already added hosts module), after entering `adb shell`:

```
su
cd /data/adb/modules
cp -a hosts badmodule
cd badmodule
rm ./disable
rm ./system/etc/hosts
rmdir ./system/etc/
mkdir ./system/lib/
touch ./system/lib/libc.so
touch ./system/lib64/libc.so
reboot
```

**Comment by newbit1** [comment]
thanks! Can't find any [module](https://github.com/Magisk-Modules-Repo?q=hosts&type=&language=&sort=) with this name.
Can you provide me a link please?

**Comment by andronoob** [comment]
>Can't find any module with this name.

It can be added by clicking "Systemless hosts" in magisk app settings.

**Comment by newbit1** [comment]
Thank you for your patience. Readme is updated.
