### ISSUE TITLE
Magisk v25.1

### ISSUE THREAD

**Issue by neomafo88** [newbit1/rootAVD#31]
Latest release https://github.com/topjohnwu/Magisk/releases/latest is Magisk v25.1
Update from existing Magisk.zip (v24.1)

**Comment by newbit1** [comment]
Thanks, is this an issue? Or just an information?

**Comment by neomafo88** [comment]
I think just information, like notification, to update this code repository to latest version

**Comment by newbit1** [comment]
i am not sure if i will update this. There is an integrated update update function within rootavd. So you can update on the fly if you want. But thanks for the note.
