### ISSUE TITLE
Process stopped in "[*] Set Directorys [-] Test if ADB SHELL is workin"

### ISSUE THREAD

**Issue by marcelocp2** [newbit1/rootAVD#32]
Hello. I can't get out of this part of the video tutorial. can you help me? Where am I wrong? I did everything as ordered in the system variables :/

![image](https://user-images.githubusercontent.com/109325818/179140533-969c2e24-8807-4115-83a7-b896147098c3.png)

![image](https://user-images.githubusercontent.com/109325818/179141004-674d4c23-ab3b-489f-a9d4-3076e8ec2030.png)

**Comment by marcelocp2** [comment]
remembering that the power shell is in administrator mode. I've also tried using the command prompt and I couldn't, it has the same error.

**Comment by newbit1** [comment]
Hi @marcelocp2 ,
PS doesnt work, yes i would have say try
cmd shell instead.

if you run adb shell, does it connect to the avd?

**Comment by newbit1** [comment]
The Gifs are showing it very detailed.

Open cmd shell, via windows key + r, and then type cmd. In there type adb shell and see if it is connecting to the avd. The avd must be running.

**Comment by marcelocp2** [comment]
![image](https://user-images.githubusercontent.com/109325818/179217265-74e49ad3-d001-478a-a009-def060ca0a89.png)

![image](https://user-images.githubusercontent.com/109325818/179217422-0c47ca60-ae90-408b-98be-72c1fc1d435a.png)

**Comment by marcelocp2** [comment]
Now, I don't know what I did, but I managed to change. I just opened powershell today, gave the command "listallavds" and then tested installapps... It returned this:

![image](https://user-images.githubusercontent.com/109325818/179219166-59a2da42-d341-4551-a405-e78d4d7295e4.png)


It is still different from what appears in your video. But is it right?

**Comment by marcelocp2** [comment]
PS C:\Users\User\Desktop\rootAVD> .\rootAVD.bat C:\Users\User\AppData\Local\Android\Sdk\system-images\android-30\google_apis_playstore\x86_64\ramdisk.img
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] ADB connectoin possible
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] looking for Magisk installer Zip
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] C:\Users\User\Desktop\rootAVD\Magisk.zip: 1 file pushed, 0 skipped. 219.3 MB/s (10641074 bytes in 0.046s)
[-] Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] C:\Users\User\AppData\Local\Android\Sdk\system-images\android-30\google_apis_playstore\x86_64\ramdisk.img: 1 file pushed, 0 skipped. 232.8 MB/s (1854025 bytes in 0.008s)
[-] Copy rootAVD Script into Magisk DIR
rootAVD.sh: 1 file pushed, 0 skipped. 100.2 MB/s (7847772 bytes in 0.075s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform: x64
[-] ARCH32 x86
[-] Device SDK API: 30
[-] First API Level: 30
[-] The AVD runs on Android 11
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[s] (s)how all available Magisk Versions
[1] local stable '24.1' (ENTER)
[2] stable 25.1
[3] canary 9183a0a6(25101)
[4] alpha 0b26882f-alpha(25101)
[-] You choose Magisk local stable Version '24.1'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '24.1' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[*] copy x86 files to /data/data/com.android.shell/Magisk/lib/x86_64
[-] copy all x86_64 files from /data/data/com.android.shell/Magisk/lib/x86_64 to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses gzip compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[*] After decompressing ramdisk.img, magiskboot will work
.\rootAVD.bat : Detected format: [gzip]
No linha:1 caractere:1
+ .\rootAVD.bat C:\Users\User\AppData\Local\Android\Sdk\system-images\a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Detected format: [gzip]:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
[-] Test patch status and do restore
[-] Checking ramdisk status
[-] STATUS=1
[-] Magisk patched boot image detected
[-] Constructing environment - PAY ATTENTION to the AVDs Screen
[!] not root yet
[!] Couldn't construct environment
[!] Double Check Root Access
[!] Re-Run Script with clean ramdisk.img and try again
[!] aborting the script

**Comment by newbit1** [comment]
Use the cmd shell, not the power shell.
The youtube video is not from me ans it is wrong, it starts with the installapps command which is the wrong command to start with. Adb connects fine via cmd shell. Restore your ramdisk and try again, just with the link to your ramdisk file as a parameter. Seems good so far

**Comment by marcelocp2** [comment]
How do I uninstall EVERYTHING to start the whole process from scratch your way?

**Comment by newbit1** [comment]
rootavd.bat <link to your ramdisk> restore

**Comment by marcelocp2** [comment]
I managed to get it working using the command rootadv.bat restore

But now I run into another problem:



![image](https://user-images.githubusercontent.com/109325818/179269889-daecc898-ab2d-45b6-9766-e4ed81b981c5.png)
Can you help me? Could you give me some contact so I can explain in more detail what I'm trying to do? I promise you it wouldn't take more than 5 minutes...

**Comment by newbit1** [comment]
is this a new issue? Or not even rootavd related? Please close the issue if so. My support ends here. You can ask on XDA
