### ISSUE TITLE
how to activate safetynet?

### ISSUE THREAD

**Issue by marcelocp2** [newbit1/rootAVD#33]
Hello how are you? I hope you're well. First I would like to apologize for the confusion created yesterday in my topic. It's the first time I'm dealing with rooted and right away it was by emulator. Secondly, I would like to thank you for the tutorial and your patience.
Today I really DISCOVERED what I need.

Can you help me?

I need to pass safetynet checks to access banking apps through android emulator. However, I've tried every possible way with safetynet kdragon, prompconfs and everything else. I've watched all the tutorials available on youtube possible, but the problem is that these tutorials only show how to do this through a real cell phone and not through an emulator. Would you help me?

**Comment by newbit1** [comment]
[Double Post](https://forum.xda-developers.com/t/script-rootavd-root-your-android-studio-virtual-device-emulator-with-magisk-android-12-linux-darwin-macos-win-google-play-store-apis.4218123/post-87161577)
