### ISSUE TITLE
Add support for A12 under Linux

### ISSUE THREAD

**Issue by 1RandomDev** [newbit1/rootAVD#36]
I really need to test something with root on a virtual device without Google Services, but currently there is no version of Android 13 that has absolutely no Google APIs etc. So is it possible to add support for rooting Android 12 under Linux?

**Comment by newbit1** [comment]
Linux is fully supported! Do you stuck somewhere in particular?

**Comment by 1RandomDev** [comment]
Nice works perfectly fine, don't know why I messed it up the last time. But then it would be really helpful to update the CompatibilityChart.md, which currently only mentions linux for A13.

**Comment by newbit1** [comment]
True, this comes from the fact, that the Images are the same since a while now. Let me think of something that can mirror this in the chart as well. Thanks for your feedback.
