### ISSUE TITLE
Mac m2 Android7.1.1 - Extracting busybox from script...

### ISSUE THREAD

**Issue by soibhanZhangxb** [newbit1/rootAVD#41]
After the attempt to “Extracting busybox from script”  I've got the following log output:
Then no longer continue the execution

(base) ➜  rootAVD ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 294.2 MB/s (10641074 bytes in 0.034s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/soibhan/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 515.8 MB/s (1463744 bytes in 0.003s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 365.5 MB/s (7850453 bytes in 0.020s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 25
[-] First API Level:
[-] The AVD runs on Android 7.1.1
[-] Switch to the location of the script file
[*] Extracting busybox from script ...

Other Android versions 10,11,12 are very well supported， but 7！

**Comment by newbit1** [comment]
I am sorry that the script fails on 7.1.1. I can't test arm AVDs.
If you want, you got the function `ExtractBusyboxFromScript() {`
and insert `set -x` to next line, and run the script again.
That way you can see what happens. Post me that log and I could know a but more.

**Comment by vanelizarov** [comment]
Same thing for Android 9

**Comment by soibhanZhangxb** [comment]
Here are the logs after setting set -x
The same happens, and the simulator screen always flashes between the black screen and the normal screen

(base) ➜  ~ adb root
restarting adbd as root
(base) ➜  rootAVD ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 388.4 MB/s (10641074 bytes in 0.026s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/soibhan/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 833.9 MB/s (1463744 bytes in 0.002s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 667.9 MB/s (12602061 bytes in 0.018s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 25
[-] First API Level:
[-] The AVD runs on Android 7.1.1
[-] Switch to the location of the script file
+ typeset 'BBSCR=/data/data/com.android.shell/Magisk/bbscript.sh'
+ typeset 'bblineoffset='
+ typeset 'last_line='
+ typeset 'bbline_cnt='
+ cp /data/data/com.android.shell/Magisk/rootAVD.sh /data/data/com.android.shell/Magisk/bbscript.sh
+ sort -nr
+ sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
+ bblineoffset=$'50307\n34688\n19939\n2432\n1074\n1023\n1022'
+ sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
+ sort -nr
+ sed -n '$='
[*] Extracting busybox from script ...
+ bbline_cnt=7
+ echo '[*] Extracting busybox from script ...'
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,50307d,50307q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,34688d,34688q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,19939d,19939q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,2432d,2432q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,1074d,1074q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox

**Comment by newbit1** [comment]
> Same thing for Android 9 (API 28)
> 
> Here are the logs after setting `set -x`
> 
> ```
> ./rootAVD.sh ~/Library/Android/sdk/system-images/android-28/google_apis/arm64-v8a/ramdisk.img
> [!] and we are NOT in an emulator shell
> [*] Set Directorys
> [-] Test if ADB SHELL is working
> [-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
> [*] Cleaning up the ADB working space
> [*] Creating the ADB working space
> [-] Magisk installer Zip exists already
> [*] Push Magisk.zip into /data/data/com.android.shell/Magisk
> [-] ./Magisk.zip: 1 file pushed, 0 skipped. 362.7 MB/s (11278270 bytes in 0.030s)
> [-] ramdisk.img Backup exists already
> [*] Push ramdisk.img into /data/data/com.android.shell/Magisk
> [-] /Users/vanelizarov/Library/Android/sdk/system-images/android-28/google_apis/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 524.8 MB/s (1547364 bytes in 0.003s)
> [*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
> [-] rootAVD.sh: 1 file pushed, 0 skipped. 825.3 MB/s (7853583 bytes in 0.009s)
> [-] run the actually Boot/Ramdisk/Kernel Image Patch Script
> [*] from Magisk by topjohnwu and modded by NewBit XDA
> [!] We are in a ranchu emulator shell
> [-] Api Level Arch Detect
> [-] Device Platform is arm64 only
> [-] Device SDK API: 28
> [-] First API Level: 28
> [-] The AVD runs on Android 9
> [-] Switch to the location of the script file
> + typeset 'BBSCR=/data/data/com.android.shell/Magisk/bbscript.sh'
> + typeset 'bblineoffset='
> + typeset 'last_line='
> + typeset 'bbline_cnt='
> + cp /data/data/com.android.shell/Magisk/rootAVD.sh /data/data/com.android.shell/Magisk/bbscript.sh
> + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> + sort -nr
> + bblineoffset=$'31601\n24906\n15357\n2553\n1087\n1036\n1035' 
> + sort -nr
> + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> + sed -n '$='
> + bbline_cnt=7 
> + echo '[*] Extracting busybox from script ...'
> [*] Extracting busybox from script ...
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,31601d,31601q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null 
> + 2>&1 
> + /data/data/com.android.shell/Magisk/busybox
> + 
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,24906d,24906q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null 
> + 2>&1 
> + /data/data/com.android.shell/Magisk/busybox
> + 
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,15357d,15357q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null 
> + 2>&1 
> + /data/data/com.android.shell/Magisk/busybox
> ```

Android 9 is not supported at all!
But thw script runs fine though. How long did you wait?

**Comment by newbit1** [comment]
> Here are the logs after setting set -x
> The same happens, and the simulator screen always flashes between the black screen and the normal screen
> 
> (base) ➜  ~ adb root
> restarting adbd as root
> (base) ➜  rootAVD ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img
> [!] and we are NOT in an emulator shell
> [*] Set Directorys
> [-] Test if ADB SHELL is working
> [-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
> [*] Cleaning up the ADB working space
> [*] Creating the ADB working space
> [-] Magisk installer Zip exists already
> [*] Push Magisk.zip into /data/data/com.android.shell/Magisk
> [-] ./Magisk.zip: 1 file pushed, 0 skipped. 388.4 MB/s (10641074 bytes in 0.026s)
> [-] ramdisk.img Backup exists already
> [*] Push ramdisk.img into /data/data/com.android.shell/Magisk
> [-] /Users/soibhan/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 833.9 MB/s (1463744 bytes in 0.002s)
> [*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
> [-] rootAVD.sh: 1 file pushed, 0 skipped. 667.9 MB/s (12602061 bytes in 0.018s)
> [-] run the actually Boot/Ramdisk/Kernel Image Patch Script
> [*] from Magisk by topjohnwu and modded by NewBit XDA
> [!] We are in a ranchu emulator shell
> [-] Api Level Arch Detect
> [-] Device Platform is arm64 only
> [-] Device SDK API: 25
> [-] First API Level:
> [-] The AVD runs on Android 7.1.1
> [-] Switch to the location of the script file
> + typeset 'BBSCR=/data/data/com.android.shell/Magisk/bbscript.sh'
> + typeset 'bblineoffset='
> + typeset 'last_line='
> + typeset 'bbline_cnt='
> + cp /data/data/com.android.shell/Magisk/rootAVD.sh /data/data/com.android.shell/Magisk/bbscript.sh
> + sort -nr
> + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> + bblineoffset=$'50307\n34688\n19939\n2432\n1074\n1023\n1022'
> + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> + sort -nr
> + sed -n '$='
> [*] Extracting busybox from script ...
> + bbline_cnt=7
> + echo '[*] Extracting busybox from script ...'
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,50307d,50307q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null
> + 2>&1
> + /data/data/com.android.shell/Magisk/busybox
> +
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,34688d,34688q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null
> + 2>&1
> + /data/data/com.android.shell/Magisk/busybox
> +
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,19939d,19939q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null
> + 2>&1
> + /data/data/com.android.shell/Magisk/busybox
> +
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,2432d,2432q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null
> + 2>&1
> + /data/data/com.android.shell/Magisk/busybox
> +
> + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> + sed -i 1,1074d,1074q /data/data/com.android.shell/Magisk/busybox
> + >/dev/null
> + 2>&1
> + /data/data/com.android.shell/Magisk/busybox

Same here, the script runs fine. It finds all the busybox versions and extract it. How long did you wait?

**Comment by soibhanZhangxb** [comment]
I tested both version of default and google-apis,  both were completed and restarted successfully. But magisk was not successfully installed.

default and google-apis performed about more than three minutes and five minutes each

**Comment by soibhanZhangxb** [comment]
Did not wait so long before, feel dead and forced to end, this time useless "adb root", before others said to use。

**Comment by newbit1** [comment]
So in short, the `[*] Extracting busybox from script ...` function actually does finish, after a longer time than usual.
But Magisk wasn't successfully installed after all? Could you please post the full log now?
Also, did you do a cold reboot of the AVD? so that the patched ramdisk.img gets loaded.

**Comment by vanelizarov** [comment]
> > Same thing for Android 9 (API 28)
> > 
> > Here are the logs after setting `set -x`
> > 
> > ```
> > ./rootAVD.sh ~/Library/Android/sdk/system-images/android-28/google_apis/arm64-v8a/ramdisk.img
> > [!] and we are NOT in an emulator shell
> > [*] Set Directorys
> > [-] Test if ADB SHELL is working
> > [-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
> > [*] Cleaning up the ADB working space
> > [*] Creating the ADB working space
> > [-] Magisk installer Zip exists already
> > [*] Push Magisk.zip into /data/data/com.android.shell/Magisk
> > [-] ./Magisk.zip: 1 file pushed, 0 skipped. 362.7 MB/s (11278270 bytes in 0.030s)
> > [-] ramdisk.img Backup exists already
> > [*] Push ramdisk.img into /data/data/com.android.shell/Magisk
> > [-] /Users/vanelizarov/Library/Android/sdk/system-images/android-28/google_apis/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 524.8 MB/s (1547364 bytes in 0.003s)
> > [*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
> > [-] rootAVD.sh: 1 file pushed, 0 skipped. 825.3 MB/s (7853583 bytes in 0.009s)
> > [-] run the actually Boot/Ramdisk/Kernel Image Patch Script
> > [*] from Magisk by topjohnwu and modded by NewBit XDA
> > [!] We are in a ranchu emulator shell
> > [-] Api Level Arch Detect
> > [-] Device Platform is arm64 only
> > [-] Device SDK API: 28
> > [-] First API Level: 28
> > [-] The AVD runs on Android 9
> > [-] Switch to the location of the script file
> > + typeset 'BBSCR=/data/data/com.android.shell/Magisk/bbscript.sh'
> > + typeset 'bblineoffset='
> > + typeset 'last_line='
> > + typeset 'bbline_cnt='
> > + cp /data/data/com.android.shell/Magisk/rootAVD.sh /data/data/com.android.shell/Magisk/bbscript.sh
> > + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> > + sort -nr
> > + bblineoffset=$'31601\n24906\n15357\n2553\n1087\n1036\n1035' 
> > + sort -nr
> > + sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
> > + sed -n '$='
> > + bbline_cnt=7 
> > + echo '[*] Extracting busybox from script ...'
> > [*] Extracting busybox from script ...
> > + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> > + sed -i 1,31601d,31601q /data/data/com.android.shell/Magisk/busybox
> > + >/dev/null 
> > + 2>&1 
> > + /data/data/com.android.shell/Magisk/busybox
> > + 
> > + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> > + sed -i 1,24906d,24906q /data/data/com.android.shell/Magisk/busybox
> > + >/dev/null 
> > + 2>&1 
> > + /data/data/com.android.shell/Magisk/busybox
> > + 
> > + cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
> > + sed -i 1,15357d,15357q /data/data/com.android.shell/Magisk/busybox
> > + >/dev/null 
> > + 2>&1 
> > + /data/data/com.android.shell/Magisk/busybox
> > ```
> 
> Android 9 is not supported at all!
> But thw script runs fine though. How long did you wait?

Uh, I've waited about 5 or 10 minutes and canceled the process. Maybe I really should wait a lil bit longer.

Btw, what do you mean by Android 9 is not supported at all? The root will not work completely or work but with some issues?

All I need is a basic access to `/system` directory in r/w mode to install custom system apps. On Android 11 AVD it is not possible, because since v10 `/` and `/system` are not capable to mount in r/w mode, only in readonly.

**Comment by newbit1** [comment]
Check out the readme, there is link to the aosp explanation. In short, the ramdisk.img is just a dummy file. Android 9 uses an internal ramdisk which we cannot access. With magisk you dont need system r/w. If you wanr to mod files there, you have to use a module with magisk.

**Comment by soibhanZhangxb** [comment]
1.  I install android 7.1.1 emulator from new one. 
2.  Then execute rootAVD # ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img
3.  After waitting for about seven  minutes, the system begen to restart.
4.  I stared it cold once again,   didn't see the magisk.

(base) ➜  rootAVD ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 290.8 MB/s (10641074 bytes in 0.035s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/soibhan/Library/Android/sdk/system-images/android-25/default/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 1252.6 MB/s (1463744 bytes in 0.001s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 569.4 MB/s (12602061 bytes in 0.021s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 25
[-] First API Level:
[-] The AVD runs on Android 7.1.1
[-] Switch to the location of the script file
+ typeset 'BBSCR=/data/data/com.android.shell/Magisk/bbscript.sh'
+ typeset 'bblineoffset='
+ typeset 'last_line='
+ typeset 'bbline_cnt='
+ cp /data/data/com.android.shell/Magisk/rootAVD.sh /data/data/com.android.shell/Magisk/bbscript.sh
+ sort -nr
+ sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
+ bblineoffset=$'50307\n34688\n19939\n2432\n1074\n1023\n1022'
+ sed -n '/BUSYBOXBINARY/=' /data/data/com.android.shell/Magisk/bbscript.sh
+ sed -n '$='
+ sort -nr
+ bbline_cnt=7
[*] Extracting busybox from script ...
+ echo '[*] Extracting busybox from script ...'
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,50307d,50307q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,34688d,34688q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,19939d,19939q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,2432d,2432q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
+
+ cp /data/data/com.android.shell/Magisk/bbscript.sh busybox
+ sed -i 1,1074d,1074q /data/data/com.android.shell/Magisk/busybox
+ >/dev/null
+ 2>&1
+ /data/data/com.android.shell/Magisk/busybox
(base) ➜  rootAVD

**Comment by soibhanZhangxb** [comment]
1. I test google-apis 7.1.1 again.
Then execute rootAVD # ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/google-apis/arm64-v8a/ramdisk.img
After waitting for about fourteen minutes, the system begen to restart.
I stared it cold once again, didn't see the magisk.

**Comment by vanelizarov** [comment]
> Check out the readme, there is link to the aosp explanation. In short, the ramdisk.img is just a dummy file. Android 9 uses an internal ramdisk which we cannot access. With magisk you dont need system r/w. If you wanr to mod files there, you have to use a module with magisk.

Oh, I've missed the explanation in readme, thanks for pointing out!

Can you please suggest which Magisk module should I use? I've seen overlayfs-based but It didn't work saying something like "your distro doesn'y support overlayfs"

**Comment by newbit1** [comment]
You have to write your own module, according to your needs.

**Comment by newbit1** [comment]
> 1. I test google-apis 7.1.1 again.
> Then execute rootAVD # ./rootAVD.sh ~/Library/Android/sdk/system-images/android-25/google-apis/arm64-v8a/ramdisk.img
> After waitting for about fourteen minutes, the system begen to restart.
> I stared it cold once again, didn't see the magisk.
> 

This is way too long for the script. Skip A7 and use another one. I am sorry that I cant help you further.
