### ISSUE TITLE
Command Examples list is empty & ListAllAVDs not working

### ISSUE THREAD

**Issue by oom-** [newbit1/rootAVD#42]
I'm on windows :
```
WindowsBuildLabEx                                       : 19041.1.amd64fre.vb_release.191206-1406
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 25/10/2020 22:42:20
WindowsProductId                                        : 00330-80192-25494-AA258
WindowsProductName                                      : Windows 10 Pro
```
I get no commands examples as list:
![image](https://user-images.githubusercontent.com/11071671/201540749-bd2ac699-1cf8-4760-b59b-2f8681a2874d.png)

And the command ListAllAVDs is not working, displaying the help again. (I'm using CMD and not PowerShell)

**Comment by oom-** [comment]
Seems to have worked by passing the `ramdisk.img` (not existing) to the command line : `rootAVD.bat D:\AndroidSDK\system-images\android-30\google_apis\x86_64\ramdisk.img`

**Comment by newbit1** [comment]
Did you install any AVD images yet?

**Comment by oom-** [comment]
Yes I did. 28/29/30.  All this part of thethe path is actually existing: `D:\AndroidSDK\system-images\android-30\google_apis\x86_64\`. Could they are on another disk ?

**Comment by newbit1** [comment]
Yes, i am just looking in the standard dir. Is this other location some how populated?
