### ISSUE TITLE
Nothing Happend or Something i do is missing out?

### ISSUE THREAD

**Issue by nikkoenggaliano** [newbit1/rootAVD#43]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/37658579/201582845-e04bc9c7-5ca3-4a06-b460-ae4da00895b2.png">

Im running the script and not same as the gif on windows 11 API 29, the script finish in process 

```
[*] repacking back to ramdisk.img format
[!] Rename Magisk.zip to Magisk.apk
```

**Comment by newbit1** [comment]
Can you please post the full log?
Incl. the start command

**Comment by newbit1** [comment]
If this issues persist, open a new issue with the full log.
