### ISSUE TITLE
The AVD can't start 

### ISSUE THREAD

**Issue by nevinhappy** [newbit1/rootAVD#44]
[INFO]
platfrom : MacOS
AVD: Pixel 6 API 31 Android 12.0 | Arm64

[Result]
After run the script, and get hint of reboot AVD; I did it manually, but AVD started with black screen.

**Comment by newbit1** [comment]
Which Magisk Version? The AVD should shot down by the script. Can you provide a full log?

**Comment by nevinhappy** [comment]
> Which Magisk Version? The AVD should shot down by the script. Can you provide a full log?

![TMP9](https://user-images.githubusercontent.com/1475079/203455027-4ae147bf-0b9e-4691-9cf0-3f2cf3f0c6d6.png)

**Comment by newbit1** [comment]
Cant really see the installed Magisk Version. But log seems fine to me.
To create a more readable log, just copy & paste the terminals output. Like this one [here](https://github.com/newbit1/rootAVD/issues/47#issue-1462341887)

**Comment by nevinhappy** [comment]
> here
xxx-MacBook-Pro rootAVD % ./rootAVD.sh ~/Library/Android/sdk/system-images/android-31/default/arm64-v8a/ramdisk.img
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 342.8 MB/s (11278270 bytes in 0.031s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/xxx/Library/Android/sdk/system-images/android-31/default/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 432.6 MB/s (4685032 bytes in 0.010s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 355.6 MB/s (7855770 bytes in 0.021s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 31
[-] First API Level: 31
[-] The AVD runs on Android 12
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[s] (s)how all available Magisk Versions
[1] local stable '25.2' (ENTER)
[2] stable 25.2
[3] canary a468fd94(25205)
[4] alpha 44643ad7-alpha(25205)
[-] You choose Magisk local stable Version '25.2'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '25.2' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[-] copy all arm64-v8a files from /data/data/com.android.shell/Magisk/lib/arm64-v8a to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses lz4_legacy compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[*] After decompressing ramdisk.img, magiskboot will work
Detected format: [lz4_legacy]
[-] Checking ramdisk STATUS=1
[-] Magisk patched boot image detected
[*] Verifying Boot Image by its Kernel Release number:
[-] This AVD = 5.10.110-android12-9-00004-gb92ac325368e-ab8731800
[-]  Ramdisk = 5.10.110-android12-9-00004-gb92ac325368e-ab8731800
[!] Ramdisk is probably from this AVD
[*] repacking back to ramdisk.img format
[!] Rename Magisk.zip to Magisk.apk
[*] Pull ramdiskpatched4AVD.img into ramdisk.img
[-] /data/data/com.android.shell/Magisk/ramdiskpatched4AVD.img: 1 file pulled, 0 skipped. 456.6 MB/s (4685032 bytes in 0.010s)
[*] Pull Magisk.apk into 
[-] /data/data/com.android.shell/Magisk/Magisk.apk: 1 file pulled, 0 skipped. 366.1 MB/s (11278270 bytes in 0.029s)
[-] Clean up the ADB working space
[-] Install all APKs placed in the Apps folder
[*] Trying to install Apps/Magisk.apk
[*] Performing Streamed Install
[*] Success
[-] Shut-Down & Reboot (Cold Boot Now) the AVD and see if it worked
[-] Root and Su with Magisk for Android Studio AVDs
[-] Trying to shut down the AVD
[!] If the AVD doesn't shut down, try it manually!
[-] Modded by NewBit XDA - Jan. 2021
[!] Huge Credits and big Thanks to topjohnwu, shakalaca, vvb2060 and HuskyDG

**Comment by newbit1** [comment]
Thanks! It seems the ramdisk is already patched. Try to restore it. Just add restore after your start command and try it again. The works best with a stock, unmodified ramdisk.

**Comment by nevinhappy** [comment]
> Thanks! It seems the ramdisk is already patched. Try to restore it. Just add restore after your start command and try it again. The works best with a stock, unmodified ramdisk.

I did restore, and the AVD works ok.
