### ISSUE TITLE
keep Extracting busybox from script for about half hour,and AVD freeze up

### ISSUE THREAD

**Issue by yushusu** [newbit1/rootAVD#45]
./rootAVD.sh ~/Library/Android/sdk/system-images/android-28/google_apis_playstore/arm64-v8a/ramdisk.img
[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 511.5 MB/s (11278270 bytes in 0.021s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/xxx/Library/Android/sdk/system-images/android-28/google_apis_playstore/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 1062.5 MB/s (1506130 bytes in 0.001s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 946.4 MB/s (7855302 bytes in 0.008s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 28
[-] First API Level: 28
[-] The AVD runs on Android 9
[-] Switch to the location of the script file
[*] Extracting busybox from script ...

**Comment by newbit1** [comment]
Android 9 is not supported!

**Comment by PATAPOsha** [comment]
what Android versions are supported?
