### ISSUE TITLE
Request for latest version including the zip

### ISSUE THREAD

**Issue by geetaroraqaz** [newbit1/rootAVD#46]
I previously installed the 24.1 version provided in this repo but now unable to upgrade the zip to 25.2 version
I chose the latest version from the options in .sh file but still the magisk app is showing prev version
Also, upgrading from magisk app is not working somehow.
Therefore requesting a fix and an updated zip
thanks

**Comment by newbit1** [comment]
This isn't an issue with the script. Updating Magisk from the App works fine. If you wanna upgrade the ramdisk as well via the App, you have to use the FAKEBOOTIMG argument.

**Comment by geetaroraqaz** [comment]
Thank you for your response
Can you please share any tutorial or script that I can follow as I'm unable
to find this
Thanks again

**Comment by newbit1** [comment]
https://github.com/newbit1/rootAVD/blob/master/README.md#fake-bootimg-on-macos
