### ISSUE TITLE
Script problem with Split APK's

### ISSUE THREAD

**Issue by jswinss** [newbit1/rootAVD#50]
The script seems to hang indefinitely when split APK's are brought into the equation. Any ideas to get around this?

- I am using the following command: `sudo ./rootAVD.sh ~/Library/Android/sdk/system-images/android-33/google_apis/arm64-v8a/ramdisk.img`
- I am also on Mac OS
- The message that it is hanging on is "Trying to install Apps/split_config.arm64.apk"
- The base APK is able to be transferred but not any of the APK's
- I removed the split APK's from /App and the base APK was transferred. But, the moment I placed them back, the script would hang again

**Comment by newbit1** [comment]
Hi @jswinss ,
if you provide me a link to that split apk.
I will have a look into this.
Cheers
NewBit

**Comment by newbit1** [comment]
Hey @jswinss ,
you could try this to see if it works
with your apk.

[Manually installing split APK files App Bundles via ADB](https://raccoon.onyxbits.de/blog/install-split-apk-adb/)
