### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by hansmbakker** [newbit1/rootAVD#51]
Did anybody try this with an Android TV image in the emulator?

I tried on Windows 11 with the default `Android TV - 1080p` base device from the device manager.
It has these settings:
- processor: x86
- OS: Android 12.0 - API31

`adb shell` just opens once, but quits on later tries.

After starting the emulator, the `rootAVD ListAllAVDs` returns only the default options and does not seem to detect the emulator.

![image](https://user-images.githubusercontent.com/3463496/211222490-df928847-e4a0-4a38-902a-430d911945d1.png)

**Comment by newbit1** [comment]
No i didnt try Android TV yet.
Regarsing the ListAllAvds, check if your installation folder is in the standard path.

**Comment by hansmbakker** [comment]
> check if your installation folder is in the standard path

`adb` is installed in `C:\Program Files (x86)\Android\android-sdk\platform-tools` - that sounds quite standard?

**Comment by newbit1** [comment]
I meant the path where your system images are stored. Standard on windows is '%LOCALAPPDATA%\Android\Sdk\system-images\'

**Comment by hansmbakker** [comment]
The folder you mentioned does not exist on my computer, but for me the `system-images` folder is at ` C:\Program Files (x86)\Android\android-sdk\system-images`

The emulator image is stored at `C:\Users\<user-folder>\.android\avd\android_tv_1080p_-_api_31.avd`

**Comment by newbit1** [comment]
> `adb` is installed in `C:\Program Files (x86)\Android\android-sdk\platform-tools` - that sounds quite standard?

Windows Standard for Programs yes, but not for Android Studio Files, don't ask me why.
> The folder you mentioned does not exist on my computer, but for me the `system-images` folder is at ` C:\Program Files (x86)\Android\android-sdk\system-images`

You see, this is not Android Studio Standard, that is why the script doesn't find it.
So either change it back to the default folders into `%LOCALAPPDATA%\Android`
Or  use the complete path to your ramdisk.img within your present directory i.e.
`"C:\Program Files (x86)\Android\android-sdk\system-images\android-31\google_apis_playstore\x86_64\ramdisk.img"`

I will see If I include the program files directory within the search. It is after all, like you said, quite standard this folder.
