### ISSUE TITLE
Black Screen after successfully running

### ISSUE THREAD

**Issue by lephuhung** [newbit1/rootAVD#52]
OS: Macos 13.2
CPU: Apple M1 Pro
Android Studio: 2022.1.1
API: Pixel 4 -30 arm64, api 28, api 31

Everything run successfully, but emulator shutdown and not restart. I manually restart but emulator black screen

**Comment by newbit1** [comment]
Please provide the full log incl your command.

**Comment by lephuhung** [comment]
i don't save it but it show run successfully and  emulator shut down, but not restart. When i restart it black screen

**Comment by newbit1** [comment]
Then please repeat the process and copy the log.

**Comment by lephuhung** [comment]
> Then please repeat the process and copy the log.

[!] and we are NOT in an emulator shell
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[-] Magisk installer Zip exists already
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] ./Magisk.zip: 1 file pushed, 0 skipped. 297.8 MB/s (11278270 bytes in 0.036s)
[-] ramdisk.img Backup exists already
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] /Users/lph77/Library/Android/sdk/system-images/android-30/google_apis_playstore/arm64-v8a/ramdisk.img: 1 file pushed, 0 skipped. 440.4 MB/s (1757332 bytes in 0.004s)
[*] Push rootAVD.sh into /data/data/com.android.shell/Magisk
[-] rootAVD.sh: 1 file pushed, 0 skipped. 171.2 MB/s (7855800 bytes in 0.044s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is arm64 only
[-] Device SDK API: 30
[-] First API Level: 30
[-] The AVD runs on Android 11
[-] Switch to the location of the script file
[*] Extracting busybox and Magisk.zip ...
[-] Checking AVDs Internet connection...
[!] AVD is online
[!] Checking available Magisk Versions
[?] Choose a Magisk Version to install and make it local
[s] (s)how all available Magisk Versions
[1] local stable '25.2' (ENTER)
[2] stable 25.2
[3] canary 831a398b(25206)
[4] alpha ed37ddd5-alpha(25205)
[-] You choose Magisk local stable Version '25.2'
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '25.2' Installer
[-] Get Flags
[*] System-as-root, keep dm/avb-verity
[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=true
[*] KEEPFORCEENCRYPT=true
[-] copy all arm64-v8a files from /data/data/com.android.shell/Magisk/lib/arm64-v8a to /data/data/com.android.shell/Magisk
[*] Detecting ramdisk.img compression
[!] Ramdisk.img uses gzip compression
[-] taken from shakalaca's MagiskOnEmulator/process.sh
[*] executing ramdisk splitting / extraction / repacking
[-] API level greater then 30
[*] Check if we need to repack ramdisk before patching ..
[*] After decompressing ramdisk.img, magiskboot will work
Detected format: [gzip]
[-] Checking ramdisk STATUS=1
[-] Magisk patched boot image detected
[*] Verifying Boot Image by its Kernel Release number:
[-] This AVD = 5.4.86-android11-2-00040-g29b2beadc627-ab7157994
[-]  Ramdisk = 5.4.86-android11-2-00040-g29b2beadc627-ab7157994
[!] Ramdisk is probably from this AVD
[*] repacking back to ramdisk.img format
[!] Rename Magisk.zip to Magisk.apk
[*] Pull ramdiskpatched4AVD.img into ramdisk.img
[-] /data/data/com.android.shell/Magisk/ramdiskpatched4AVD.img: 1 file pulled, 0 skipped. 333.7 MB/s (1757332 bytes in 0.005s)
[*] Pull Magisk.apk into
[-] /data/data/com.android.shell/Magisk/Magisk.apk: 1 file pulled, 0 skipped. 447.7 MB/s (11278270 bytes in 0.024s)
[-] Clean up the ADB working space
[-] Install all APKs placed in the Apps folder
[*] Trying to install Apps/Magisk.apk
[*] Performing Streamed Install
[*] Success
[-] Shut-Down & Reboot (Cold Boot Now) the AVD and see if it worked
[-] Root and Su with Magisk for Android Studio AVDs
[-] Trying to shut down the AVD
[!] If the AVD doesn't shut down, try it manually!
[-] Modded by NewBit XDA - Jan. 2021
[!] Huge Credits and big Thanks to topjohnwu, shakalaca, vvb2060 and HuskyDG

**Comment by lephuhung** [comment]
Screen shot
<img width="1485" alt="Screenshot 2023-01-15 at 13 54 55" src="https://user-images.githubusercontent.com/20222030/212527299-29c50d61-b5b9-49ca-8ab6-4e3d79d13dd7.png">

**Comment by newbit1** [comment]
Looks good to me.
But the ramdisk.img was already patched.
```
[-] Checking ramdisk STATUS=1
[-] Magisk patched boot image detected
```
use the `restore` command to put the stock ramdisk.img back into place and try again.
Make sure, once the script has shut down the AVD, that you cold boot it.

**Comment by lephuhung** [comment]
> Looks good to me. But the ramdisk.img was already patched.
> 
> ```
> [-] Checking ramdisk STATUS=1
> [-] Magisk patched boot image detected
> ```
> 
> use the `restore` command to put the stock ramdisk.img back into place and try again. Make sure, once the script has shut down the AVD, that you cold boot it.

Worked, many thank
