### ISSUE TITLE
separate dependencies

### ISSUE THREAD

**Issue by fusionneur** [newbit1/rootAVD#54]
magisk and busybox should be downloaded locally and then pushed to avd.
in case of busybox, one can check the checksum and confirm the authenticity, rather than obfuscating busybox in the code. as an extra advantage, you make sure latest busybox is being used

For example:

download_dep.sh

```
#!/bin/sh

# DOWNLOAD MAGISK
username="topjohnwu"
repo="Magisk"

# latest stable
# magisk_URL=$(curl -s https://api.github.com/repos/$username/$repo/releases/latest | grep "browser_download_url" | grep -v stub | awk -F ['"'] '{print $4}')

# canary more compatible
magisk_URL="https://raw.githubusercontent.com/topjohnwu/magisk-files/canary/app-debug.apk"

echo "$magisk_URL"

curl -L -o magisk.apk "$magisk_URL"

# DOWNLOAD BUSYBOX

username="Magisk-Modules-Repo"
repo="busybox-ndk"

busybox_URL="https://github.com/$username/$repo/raw/master/busybox-x86_64-selinux"

curl -L -o busybox "$busybox_URL"
```

**Comment by newbit1** [comment]
Dear @fusionneur,
thank you for your request, which is not the first of this kind.
They are quite some conditions to meet to implement this. I am sure
you didn't consider all of them, If yes, I will do it as you please.
1. What is the Up-to-Date version of busybox?
2. What are the present versions of busybox in the script?
3. What tool in detail are you missing in the present busybox version? and why?
4. Does your code run in Linux/Mac/Windows?
5. Why exactly should Magisk be downloaded locally and then pushed to the avd?
6. Why exactly should busybox be downloaded locally and then pushed to the avd?
7. If you would move your code to be executed within the avd, does it also run with Android 7?
8. Or would you actually need busybox to get busybox?

**Comment by newbit1** [comment]
> **What tool in detail are you missing in the present busybox version? and why?**
> None, I believe. I tried rootAVD's yesterday with success on an android v 13 (API 33)

Thanks for your reply. So there is actually no practical reason nor a real benefit to change this.

**Comment by newbit1** [comment]
Dont use it if you dont trust it.
Easily audited for whom?

**Comment by newbit1** [comment]
It is just a script! If github is showing it not correctly, not my fault. Just dont use it, or fork it and rewrite it in your own style.

**Comment by newbit1** [comment]
Both are the same. The "chunk" is the start of one of the busybox binarys.
