### ISSUE TITLE
Black Screen after successful run

### ISSUE THREAD

**Issue by mashincode** [newbit1/rootAVD#55]
First need to say that I checked similar issues and it did not help

I am using Mac M1 and I tried to run the script with 2 different API 30 and 33, same results, after my emulator and adb closed due reloading I can't get into it, I see only a black screen and after 300 second it shot down 

I tried to use restore argument did not help

Help please :) 

Ask me any questions if needed, here is some screenshots of my last run with API 33 (Actually here i tried to run the script twice just in case maybe it will help)
 
<img width="1431" alt="Screenshot 2023-01-31 at 17 39 32" src="https://user-images.githubusercontent.com/40808855/215840240-774fe65c-eb3f-40d3-a72b-b43554bf6f17.png">

<img width="1168" alt="Screenshot 2023-01-31 at 17 39 38" src="https://user-images.githubusercontent.com/40808855/215840254-53cf6174-566d-49f3-87af-305b08ca995a.png">

**Comment by newbit1** [comment]
Looks good so far.
Your screenshots are showing that your ramdisk is already patched, but I've said you did the restore already.
Make sure If you start over that you really start with a stock ramdisk.
Once patching the stock ramdisk is completed, and the AVD window is closed, restart the AVD with the
cold boot function.

**Comment by mashincode** [comment]
Hey, just tried it

I did remove previous emulator and tried to do one more time with API 33 for Pixel 2

Now no black screen, but also no Magisk app there

Here the logs, i tried to record a video, but can't really past it here

Also before clothing it ask me to save the state of emulator, I clicked no, but if I will click yes (tried before) I think i will have the same results

If I can provide more info  I am ready to help


<img width="651" alt="Screenshot 2023-02-01 at 18 31 30" src="https://user-images.githubusercontent.com/40808855/216131586-946e6147-1e8f-4c78-91b6-a4823a93d7e3.png">

**Comment by mashincode** [comment]
Hey, that's really help, i have another issue or maybe miss understanding , should I create new issue here?

So I was able to 
- reboot with cold boot 
- i found Magisk app
-  following the gif image  I went to settings and click Zygisk check box
- reboot 
- install Magisk from Magisk app
- reboot automatically 
- then I still see button install as active and tried to run adb root receive adbd cannot run as root in production builds

<img width="406" alt="Screenshot 2023-02-01 at 18 43 58" src="https://user-images.githubusercontent.com/40808855/216135476-129b3ab7-4b4d-4006-b601-e9230a2e0c51.png">

I don't  really know what I need to do next, I am very new to Android and I just tried to setup emulator with Burp Proxy on my mac, I need to add cert there and found that only option is to have root, so that's why I am here :) If there a chance that you can show me, what I really need to do next - please

**Comment by newbit1** [comment]
> * install Magisk from Magisk app

This shouldn't be necessary if the script finished the job well.
But though it looks good your screenshot.

> tried to run adb root receive adbd cannot run as root in production builds

`adb root` invokes the internal root from AOSP, not the magisk one.
If you go into the shell, `adb shell`, and run `su`, this will prompt you the magisk su toast,
and after granting it, you are root in your shell.

My support ends here, I am sorry I can't help you with cert or proxy settings. But you can check out other issues here,
I recall that they were at least one more who asked also about this stuff.

**Comment by mashincode** [comment]
Thank you! Yes, i was looking for this SU command , other things I can handle

Thank you very much, I think I will make tutorial for other guys and i will mention your project on it, that's really useful
