### ISSUE TITLE
Env no longer constructed

### ISSUE THREAD

**Issue by androidacy-user** [newbit1/rootAVD#56]
Hello!

Magisk is no longer allowing to construct env, as it tries to update instead and fails, and FixEnvTask does nothing.

**Comment by newbit1** [comment]
Hi,

Not sure what you mean by ENV.
The command to fix this bug from an old Magisk Version is not longer implementes. Do you have screenahots or loga feom your issue?

**Comment by newbit1** [comment]
Sounds like a diffrent issues. Please more infos about youe system, the avd and the magisk version. Logfiles would be great as well.

**Comment by newbit1** [comment]
LOG FILES!!!???
