### ISSUE TITLE
rootAVD.bat does not install apps

### ISSUE THREAD

**Issue by TheOriginalBob0705** [newbit1/rootAVD#57]
`rootAVD.bat C:\Android\system-images\android-33\google_apis\x86_64\ramdisk.img` does not perform any visible change to the system

`abd` has been added to the PATH, the AVD is open and connected, `adb shell` works perfectly fine

Here is the output from attempting `rootAVD.bat C:\Android\system-images\android-33\google_apis\x86_64\ramdisk.img `:

```
[*] Set Directorys
[-] Test if ADB SHELL is working
```

This is the same output that occurs when providing the script with a ramdisk.img file

**Comment by newbit1** [comment]
is there any apk file in the Apps folder?
Do you execute the script via cmd shell or power shell?

**Comment by TheOriginalBob0705** [comment]
cmd shell
there is no apk file in my Apps folder, it only has a .gitkeep file

**Comment by TheOriginalBob0705** [comment]
powershell provides a similar output with an additional line:

```
[*] Set Directorys
[-] Test if ADB SHELL is working
else was unexpected at this time.
```

**Comment by newbit1** [comment]
CMD shell is the right one, so far so good.
If you don't have any apk in that folder, why do you want to run the InstallApps command?

This feature is only needed, if you have a bunch of apks that you don't want to install manually.

The script is mostly used with the path to the ramdisk file, thats it. Sometimes, if there was a blank space
in your path, the script crashed. But this was fixed some time ago.

**Comment by newbit1** [comment]
Where is your ADB installed?

**Comment by TheOriginalBob0705** [comment]
my adb is installed in C:\Android\platform-tools

i placed your script in C:\Android\

I have added adb to my PATH variables

**Comment by newbit1** [comment]
Ok thanks, I need to replicate that situation, to see if I can reproduce your issue.
I am sorry for your inconveniences.

**Comment by newbit1** [comment]
I am sorry, I can't reproduce your issue.
I've moved my adb like yours to c: android, and in the cmd shell,
`set PATH=C:\Android\platform-tools;%PATH%`
adb shell works, and if I run the script, it starts right away.

Is it possible, that you have more than one adb installed?
Check the closed issues, I can recall someone else had a very similar issue and fixed it.

**Comment by TheOriginalBob0705** [comment]
Thanks for the help, I managed to fix the issue by copying a ramdisk.img file over to my folder from somebody else who managed to get the script working for them. 

For anyone interested, you both have to use the exact same virtual device for this to work, both the phone and the system image have to be identical

**Comment by newbit1** [comment]
What phone image? The avd has only one ramdisk.img there is phone involved.

**Comment by newbit1** [comment]
Ah ok, you mean the picture of your frame. Got it.
