### ISSUE TITLE
Rooted by still get error

### ISSUE THREAD

**Issue by danaabhi** [newbit1/rootAVD#58]
Hi i tried all steps successfully but still i am getting Read-only file system when using cp command to copy certificate from sdcard to system.

cp: system/etc/security/cacerts/burp.cer: Read-only file system

**Comment by newbit1** [comment]
Hi, the system is not read/write mounted by default. Depending on where you want to copy from, linux shell or android shell, you have remount the system as rw, cp your files, set permissions, and remount back as read only. Check the script, inside are some remount commands used where you can pick up the syntax.

**Comment by newbit1** [comment]
https://github.com/newbit1/rootAVD/issues/41#issuecomment-1311717316
