### ISSUE TITLE
ListAllAVDs not working

### ISSUE THREAD

**Issue by AldoReghan** [newbit1/rootAVD#59]
hey can you help when i run command

rootAVD.bat ListAllAVDs

show this 

![image](https://user-images.githubusercontent.com/38031214/229692122-ceedc074-32b0-4747-afd3-d6ca08bbdfa4.png)
![image](https://user-images.githubusercontent.com/38031214/229692174-90d982c4-8946-4386-bd78-b2fdf4325dbd.png)

this is environment the emulator

![image](https://user-images.githubusercontent.com/38031214/229692709-87cd6bfb-e09c-4326-b955-ddd06e160818.png)

**Comment by newbit1** [comment]
hey,
do you have any AVDs installed? If not, there will be none displayed.

**Comment by AldoReghan** [comment]
hey, i have installed avd Pixel 4 Api 30

![image](https://user-images.githubusercontent.com/38031214/229757179-c9b73d85-ad4c-4499-a9bb-3c1b7d76197c.png)

**Comment by AldoReghan** [comment]
hey, i have installed avd Pixel 4 API 30

![image](https://user-images.githubusercontent.com/38031214/229758680-6ad3a517-6d0c-447a-8bf4-78550e0f4cb0.png)

**Comment by newbit1** [comment]
Then perhapy not im a standard folder.
