### ISSUE TITLE
Is Android 11 supported?

### ISSUE THREAD

**Issue by mihaimacarie98** [newbit1/rootAVD#62]
I've tried to use the script on two Android 11 Automotive images, but I don't get any su binary installed. It works without issues on Android 10.

Example of an image: https://developer.gm.com/downloads/final_31XX_06272022_emulator.xml

**Comment by newbit1** [comment]
Accorsing to my chart, yes it is.
Did you see the automotive notes on the readme?

**Comment by newbit1** [comment]
Ok i see.
Can you send me the full log from the android 11 try?

**Comment by newbit1** [comment]
I think I've found your issue.
They are two ramdisk files.
both of them need to be patched, then magisk will work with my notes by switching to user 0.
Rename ramdisk-qemu.img to ramdisk.img and patch it, and then rename it back.

**Comment by mihaimacarie98** [comment]
> I think I've found your issue. They are two ramdisk files. both of them need to be patched, then magisk will work with my notes by switching to user 0. Rename ramdisk-qemu.img to ramdisk.img and patch it, and then rename it back.

Hi! Thanks that was the problem. Btw: How can I reset the SuperSu permission of the shell? I failed to approve it within the time shown.

**Comment by newbit1** [comment]
you can't, you have to go into the magisk app, and allow manually

**Comment by mihaimacarie98** [comment]
> you can't, you have to go into the magisk app, and allow manually

I can't access the SuperSu tab in Magisk disk...

**Comment by newbit1** [comment]
shell is executed as user 0. the toast will show up until you switch to user 0
