### ISSUE TITLE
Execute binaries through adb shell

### ISSUE THREAD

**Issue by mihaimacarie98** [newbit1/rootAVD#63]
I have su access, but I can't run custom binaries through adb shell:
system/bin/sh: ./automotiveCanV1.0_fuzzer: can't execute: Permission denied

Any work around?

**Comment by newbit1** [comment]
I don't know.
can you provide this binary?

**Comment by mihaimacarie98** [comment]
[automotiveCanV1.zip](https://github.com/newbit1/rootAVD/files/11214076/automotiveCanV1.zip)

**Comment by newbit1** [comment]
if I move this binary to a folder where you can actually execute binarys, it runs, but it says it needs a lib file.
```
emulator:/data/data/com.android.shell $ chmod +x automotiveCanV1.0_fuzzer
emulator:/data/data/com.android.shell $ ls -l automotiveCanV1.0_fuzzer
-rwx--x--x 1 shell shell 1657920 2023-04-12 17:42 automotiveCanV1.0_fuzzer
emulator:/data/data/com.android.shell $ ./automotiveCanV1.0_fuzzer                                                
CANNOT LINK EXECUTABLE "./automotiveCanV1.0_fuzzer": library "android.hardware.automotive.can@1.0.so" not found: needed by main executable
```

even without su

**Comment by mihaimacarie98** [comment]
Ok. It seems it's just about chmod. It's pretty basic stuff, so sorry for disturbing.

**Comment by newbit1** [comment]
no problem, my pleasure.
In this automotive image is lot of stuff disabled.
Like app permissions for files and folders, installing unknown sources.
makes it difficult to operate with.

**Comment by mihaimacarie98** [comment]
I know. Actually I'm doing some research for my master thesis. Now I get DT tables errors but the I think I've compiled the binary for other Android version.

**Comment by mihaimacarie98** [comment]
The binary is a libFuzzer harness provided with AOSP and I already use the sdk_car_x86_64-userdebug emulator. My idea was to attempt running it on emulator from car manufacturers.
