### ISSUE TITLE
Stuck on windows

### ISSUE THREAD

**Issue by rossSec** [newbit1/rootAVD#65]
Hi, I'm getting an issue where it gets stuck after [!] Rename Magisk.zip to Magisk.apk

![image](https://user-images.githubusercontent.com/59896313/232276832-4cc0619f-a534-4c82-a5a7-63ae278aca7a.png)
![image](https://user-images.githubusercontent.com/59896313/232276864-d30b7fdd-44cd-43d9-b4f7-a398be450262.png)

**Comment by newbit1** [comment]
Hi,
thanks for the note. Is fixed now, please re-download the script and try again.
