### ISSUE TITLE
Not working properly in Mac M2

### ISSUE THREAD

**Issue by MatheusMarxxs** [newbit1/rootAVD#67]
Macbook Pro M2 gets stucked in
`Extracting busybox from script`

I tried with SDK API 27 and 28.

**Comment by MatheusMarxxs** [comment]
Also tried with the Genymotion for Mac M2 but looks like it only creates Android 11 AVDs

**Comment by newbit1** [comment]
Script is for AVD only, not genymotion.
Api28 is Pie, not supported at all.

api 27 should work fine.
please post the full log.
