### ISSUE TITLE
Different errors in Windows PowerShell and CMD

### ISSUE THREAD

**Issue by AcTiViSioN911** [newbit1/rootAVD#71]
Hello, how to fix this? Same error on Android 13, 12, and this 11. Do I need to downgrade android studio?

PowerShell log:
```
PS C:\Users\Admin\Desktop\rootAVD-master> ./rootAVD C:\Users\Admin\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img
[*] Set Directorys
[-] Test if ADB SHELL is working
[-] ADB connectoin possible
[-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
[*] looking for Magisk installer Zip
[*] Cleaning up the ADB working space
[*] Creating the ADB working space
[*] Push Magisk.zip into /data/data/com.android.shell/Magisk
[-] C:\Users\Admin\Desktop\rootAVD-master\Magisk.zip: 1 file pushed, 0 skipped. 394.1 MB/s (11278270 bytes in 0.027s)
[*] create Backup File
[*] Push ramdisk.img into /data/data/com.android.shell/Magisk
[-] C:\Users\Admin\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img: 1 file pushed, 0 skipped. 401.0 MB/s (1520108 bytes in 0.004s)
[-] Copy rootAVD Script into Magisk DIR
rootAVD.sh: 1 file pushed, 0 skipped. 87.1 MB/s (76191 bytes in 0.001s)
[-] run the actually Boot/Ramdisk/Kernel Image Patch Script
[*] from Magisk by topjohnwu and modded by NewBit XDA
[!] We are in a ranchu emulator shell
[-] Api Level Arch Detect
[-] Device Platform is x86 only
[-] Device SDK API: 30
[-] First API Level: 30
[-] The AVD runs on Android 11
[-] Switch to the location of the script file
[*] Looking for an unzip binary
[-] unzip binary found
[*] Extracting busybox and Magisk.zip via unzip ...
[*] Finding a working Busybox Version
[!] Found a working Busybox Version
[!] BusyBox v1.34.1-Magisk (2022-03-22 04:11:29 PDT) multi-call binary.
[*] Move busybox from lib to workdir
[-] Checking AVDs Internet connection...
[!] AVD is offline
[*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
[-] We are now in Magisk Busybox STANDALONE (D)ASH
[*] rootAVD with Magisk '25.2' Installer
[-] Get Flags
Error running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of grepError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of grepError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of grepError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of grepError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of grep[-] Encrypted data, keep forceencrypt
[*] RECOVERYMODE=false
[-] KEEPVERITY=false
[*] KEEPFORCEENCRYPT=true
Error running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of mvError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of mvError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of mvError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of mvError running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of mv[-] copy all x86 files from /data/data/com.android.shell/Magisk/lib/x86 to /data/data/com.android.shell/Magisk
Error running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of chmod[*] Detecting ramdisk.img compression
Error running /data/data/com.android.shell/Magisk/busybox: Unable to get realpath of xxd[!] Ramdisk.img uses UNKNOWN compression
[!] aborting the script
[*] Pull Magisk.zip into
[-] /data/data/com.android.shell/Magisk/Magisk.zip: 1 file pulled, 0 skipped. 365.9 MB/s (11278270 bytes in 0.029s
[-] Clean up the ADB working space
[-] Install all APKs placed in the Apps folder
[-] Shut-Down and Reboot [Cold Boot Now] the AVD and see if it worked
[-] Root and Su with Magisk for Android Studio AVDs
[-] Modded by NewBit XDA - Jan. 2021
[*] Huge Credits and big Thanks to topjohnwu, shakalaca and vvb2060
[-] Trying to shut down the AVD
[!] If the AVD doesnt shut down, try it manually!
```

**Comment by AcTiViSioN911** [comment]
Another error using CMD this time:

> C:\Users\Admin\Desktop\rootAVD-master>rootAVD.bat C:\Users\Admin\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img
> [*] Set Directorys
> [-] Test if ADB SHELL is working
> [-] ADB connectoin possible
> [-] In any AVD via ADB, you can execute code without root in /data/data/com.android.shell
> [*] looking for Magisk installer Zip
> [*] Cleaning up the ADB working space
> [*] Creating the ADB working space
> [*] Push Magisk.zip into /data/data/com.android.shell/Magisk
> [-] C:\Users\Admin\Desktop\rootAVD-master\Magisk.zip: 1 file pushed, 0 skipped. 431.2 MB/s (11278270 bytes in 0.025s)
> [-] Backup exists already
> [*] Push ramdisk.img into /data/data/com.android.shell/Magisk
> [-] C:\Users\Admin\AppData\Local\Android\Sdk\system-images\android-30\google_apis\x86\ramdisk.img: 1 file pushed, 0 skipped. 480.1 MB/s (1520108 bytes in 0.003s)
> [-] Copy rootAVD Script into Magisk DIR
> rootAVD.sh: 1 file pushed, 0 skipped. 113.2 MB/s (76191 bytes in 0.001s)
> [-] run the actually Boot/Ramdisk/Kernel Image Patch Script
> [*] from Magisk by topjohnwu and modded by NewBit XDA
> [!] We are in a ranchu emulator shell
> [-] Api Level Arch Detect
> [-] Device Platform is x86 only
> [-] Device SDK API: 30
> [-] First API Level: 30
> [-] The AVD runs on Android 11
> [-] Switch to the location of the script file
> [*] Looking for an unzip binary
> [-] unzip binary found
> [*] Extracting busybox and Magisk.zip via unzip ...
> [*] Finding a working Busybox Version
> [!] Found a working Busybox Version
> [!] BusyBox v1.34.1-Magisk (2022-03-22 04:11:29 PDT) multi-call binary.
> [*] Move busybox from lib to workdir
> [-] Checking AVDs Internet connection...
> [!] AVD is offline
> [*] Re-Run rootAVD in Magisk Busybox STANDALONE (D)ASH
> [-] We are now in Magisk Busybox STANDALONE (D)ASH
> [*] rootAVD with Magisk '25.2' Installer
> [-] Get Flags
> [-] Encrypted data, keep forceencrypt
> [*] RECOVERYMODE=false
> [-] KEEPVERITY=false
> [*] KEEPFORCEENCRYPT=true
> [-] copy all x86 files from /data/data/com.android.shell/Magisk/lib/x86 to /data/data/com.android.shell/Magisk
> [*] Detecting ramdisk.img compression
> [!] Ramdisk.img uses UNKNOWN compression
> [!] aborting the script
> [*] Pull Magisk.zip into
> [-] /data/data/com.android.shell/Magisk/Magisk.zip: 1 file pulled, 0 skipped. 367.7 MB/s (11278270 bytes in 0.029s
> [-] Clean up the ADB working space
> [-] Install all APKs placed in the Apps folder
> [-] Shut-Down and Reboot [Cold Boot Now] the AVD and see if it worked
> [-] Root and Su with Magisk for Android Studio AVDs
> [-] Modded by NewBit XDA - Jan. 2021
> [*] Huge Credits and big Thanks to topjohnwu, shakalaca and vvb2060
> [-] Trying to shut down the AVD
> [!] If the AVD doesnt shut down, try it manually!

**Comment by newbit1** [comment]
PS is not supported.
But CMD is.
Can you upload me your ramdisk.img file?

**Comment by newbit1** [comment]
The find busybox routine had false positives. It turned out, that even a busybox version compiled for different
architecture can run, but does not execute the commands right, hence the issues you had.
My apologies for your inconveniences. It should be fixed now.
