### ISSUE TITLE
Can I use %ANDROID_HOME% instead of %LOCALAPPDATA%/Android ?

### ISSUE THREAD

**Issue by xixiaxixi** [newbit1/rootAVD#74]
For some reason, my platform tools(adb)/emulator is not installed in the default dir.

**Comment by newbit1** [comment]
Not yet, but I am working on it.

**Comment by newbit1** [comment]
Hi @xixiaxixi,
I've implemented the ANDROID_HOME variable. you can use now e.g. `set ANDROID_HOME=%USERPROFILE%\Downloads\sdk` to set a custom directory.
