### ISSUE TITLE
Update for Magisk 26.1 for  Shamiko-v0.7.3-174-release.zip

### ISSUE THREAD

**Issue by freeload101** [newbit1/rootAVD#76]
I first want to say thank you for all the wonderful work I can't begin to unscrable the fu that is going on in your script to port it to powershell ... 

I am trying to integrate a safety net bypass into my project, JAMBOREE. According to a post on the XDA Developers forum ( https://forum.xda-developers.com/t/module-mod-universal-safetynet-fix.4553699/page-15) , I need to upgrade Magisk to version 26.1. Despite successfully replacing the necessary files, I keep being prompted to reboot. Should the safety net be verified before I begin debugging or monitoring traffic? Alternatively, am I misinterpreting the process entirely? Should I instead be directly hacking the apps using advanced Java coding skills, similar to methods employed by tools like RMS (Runtime Mobile Security) https://github.com/m0bilesecurity/RMS-Runtime-Mobile-Security?

here is my current setup:
https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy/blob/cd132d3fa1511b8b5832520886eb025f61fce4d4/JAMBOREE.ps1#L481

![image](https://github.com/newbit1/rootAVD/assets/4307863/02ed8d9d-f234-472b-b8c6-cc57c96d8189)
 
![image](https://github.com/newbit1/rootAVD/assets/4307863/cb3b382f-dbdc-4e61-9c86-64c6c346a21e)
![image](https://github.com/newbit1/rootAVD/assets/4307863/ceb4958a-c314-428c-887b-33f5bdc049bd)
![image](https://github.com/newbit1/rootAVD/assets/4307863/f2ea7896-03c5-4042-96e3-320dee1e52f6)

![image](https://github.com/newbit1/rootAVD/assets/4307863/2467b543-d87b-4746-8441-85b587779f14)

**Comment by newbit1** [comment]
What exactly is your issue here?
As in the readme noted, if you want to install Magisk 26.x, you have to use the FAKEBOOTIMG argument.
