### ISSUE TITLE
Magisk installed but not Rooted

### ISSUE THREAD

**Issue by itsethack** [newbit1/rootAVD#8]
Hi, 
I have an issue when use it to root my AVD Google API Playstore on Android 28 x86.
(This is my avd config.ini)
[config.txt](https://github.com/newbit1/rootAVD/files/7024878/config.txt)
![image](https://user-images.githubusercontent.com/65939746/130311047-8dcc0e89-bf1c-43bd-b6c1-942642efcb05.png)
![image](https://user-images.githubusercontent.com/65939746/130311059-07df98b4-c292-499a-9929-f011ab4e19bd.png)

This script success and Magisk installed on my AVD, but still not rooted.
![image](https://user-images.githubusercontent.com/65939746/130311103-1f266acc-5d12-4164-bbca-90c431010874.png)
<details>
![image](https://user-images.githubusercontent.com/65939746/130311103-1f266acc-5d12-4164-bbca-90c431010874.png)
</details>

Any solutions ?
I still need the Google Play Store to download the apps from there. 
if I use AVD with Google API there is no Google Play Store on there.

Thanks in advance.

**Comment by newbit1** [comment]
Use a different API!
api 28(Pie) is not supported.
ramdisk.img is ignored by this OS.
Sorry for this inconvinience.

For more and detailed information please visit and read the xda thread.

Cheers
NewBit
