### ISSUE TITLE
android 10

### ISSUE THREAD

**Issue by americanocb** [newbit1/rootAVD#80]
nao consigo ter acesso ao ab shell
instalo o magisk dentro do emulador, apos instalar dei comand adb shell, mas nao aparece que esta com root

**Comment by newbit1** [comment]
English please!

**Comment by americanocb** [comment]
> 

I rooted
all right, the magisk installed on my avd android 10 appears, but in the terminal when I use adb shell command I don't have root permission.
  adb shell
generic_x86:/ $
if i use adb root it still keeps showing up
generic_x86:/ $ and the correct thing was to appear generic_x86:/ #

**Comment by newbit1** [comment]
Yeah thats normal. You have to grant root permissions for each app. When you are on the shell, type su. And grant permission window will pop up

**Comment by americanocb** [comment]
>I want to put the frida server, but I can't.
use the commands
adb shell getprop ro.product.cpu.abi
adb push frida-server /data/local/tmp/frida-server
md5sum frida-server
adb shell md5sum /data/local/tmp/frida-server
adb shell chmod +x /data/local/tmp/frida-server
adb shell ls -lah /data/local/tmp/frida-server
adb shell
adb root
but when i put this command
adb shell /data/local/tmp/frida-server says I don't have permission.

**Comment by newbit1** [comment]
not sure if normal adb user has access to data/local/tmp. Did you checked that before in adb shell?

**Comment by americanocb** [comment]
> não tenho certeza se o usuário adb normal tem acesso a data/local/tmp. Você verificou isso antes no adb shell?

yes, I checked before, now the problem that I can't have root permission, I put adb root and it says I have root access, but when I use adb shell I don't have privilege, this only on Android 11 avd.

**Comment by newbit1** [comment]
Yeah su is valid for this session. If you invoke another one with adb push, it is gone. But they are other folders you can use. The folder rootavd is using e.g. and there is another tmp folder.

**Comment by americanocb** [comment]
> imediatamente

tell me the command you used, the parameters, if possible send a print to me brother

**Comment by newbit1** [comment]
Here are my steps:
* AVD (Android 11) is rooted and running
* `adb shell` and `su` is working
```
newbit@workdir % git clone https://github.com/6a6f6a6f/run-frida-server.git && cd run-frida-server
Cloning into 'run-frida-server'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 30 (delta 7), reused 20 (delta 4), pack-reused 0
Receiving objects: 100% (30/30), 25.30 KiB | 6.32 MiB/s, done.
Resolving deltas: 100% (7/7), done.
newbit@run-frida-server %
```
```
newbit@run-frida-server % pip install -r requirements.txt
Requirement already satisfied: colorama==0.4.5 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.4.5)
Requirement already satisfied: requests==2.31.0 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: termcolor~=1.1.0 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2023.5.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2.0.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.1.0)

[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python3.10 -m pip install --upgrade pip
newbit@run-frida-server %
```
```
newbit@run-frida-server % python3 frida-server.py 
i Using device emulator-5554 as the pwning host.
i Downloading latest frida-server for x86_64...
i frida-server downloaded and extracted at /var/folders/j3/t12jqpjn4d3gynp5l22c37vw0000gq/T/oqtmnkj5
i Starting frida-server...
i frida-server running and up!
newbit@run-frida-server % 
```

**Comment by americanocb** [comment]
> Aqui estão meus passos:
> 
> * AVD (Android 11) está enraizado e em execução
> * `adb shell`e `su`está trabalhando
> 
> ```
> newbit@workdir % git clone https://github.com/6a6f6a6f/run-frida-server.git && cd run-frida-server
> Cloning into 'run-frida-server'...
> remote: Enumerating objects: 30, done.
> remote: Counting objects: 100% (30/30), done.
> remote: Compressing objects: 100% (22/22), done.
> remote: Total 30 (delta 7), reused 20 (delta 4), pack-reused 0
> Receiving objects: 100% (30/30), 25.30 KiB | 6.32 MiB/s, done.
> Resolving deltas: 100% (7/7), done.
> newbit@run-frida-server %
> ```
> 
> ```
> newbit@run-frida-server % pip install -r requirements.txt
> Requirement already satisfied: colorama==0.4.5 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (0.4.5)
> Requirement already satisfied: requests==2.31.0 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2.31.0)
> Requirement already satisfied: termcolor~=1.1.0 in /Users/newbit/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.1.0)
> Requirement already satisfied: idna<4,>=2.5 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.4)
> Requirement already satisfied: certifi>=2017.4.17 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2023.5.7)
> Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (2.0.3)
> Requirement already satisfied: charset-normalizer<4,>=2 in /Users/newbit/homebrew/lib/python3.10/site-packages (from requests==2.31.0->-r requirements.txt (line 2)) (3.1.0)
> 
> [notice] A new release of pip is available: 23.0 -> 23.1.2
> [notice] To update, run: python3.10 -m pip install --upgrade pip
> newbit@run-frida-server %
> ```
> 
> ```
> newbit@run-frida-server % python3 frida-server.py 
> i Using device emulator-5554 as the pwning host.
> i Downloading latest frida-server for x86_64...
> i frida-server downloaded and extracted at /var/folders/j3/t12jqpjn4d3gynp5l22c37vw0000gq/T/oqtmnkj5
> i Starting frida-server...
> i frida-server running and up!
> newbit@run-frida-server % 
> ```

on android 11 the adb shell
su works, the problem is on android 10

**Comment by newbit1** [comment]
it is the same procedure on A10.

I fixed an issue with my script in the meanwhile. Re Download it and try again.
If there is another error popping up, post it here.

**Comment by americanocb** [comment]
> 

run-frida-server on  main 
➜ python3 frida-server.py
Traceback (most recent call last):
  File "/Users/mkt/run-frida-server/frida-server.py", line 17, in <module>
    from helpers.adb import get_device, run_adb_command
  File "/Users/mkt/run-frida-server/helpers/adb.py", line 88, in <module>
    tuple[int, IO[bytes] | None, IO[bytes] | None, int] | tuple[int, str, str]:
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'NoneType'
soluction?

**Comment by newbit1** [comment]
No not really.
did you install the requierments?
Do you have python3 ?

**Comment by americanocb** [comment]
> Não, na verdade não. você instalou os requisitos? Você tem python3?

tenho o python 3.9

**Comment by americanocb** [comment]
> > Não, na verdade não. você estabeleceu os requisitos? Você tem python3?
> 
yes, python 3.9

**Comment by newbit1** [comment]
then i don't know what your error message could mean. Google it.
I just tried on several other AVD images, down to 7, and they all worked just fine.

**Comment by americanocb** [comment]
> 

you used these commands only correct?
git clone https://github.com/6a6f6a6f/run-frida-server.git && cd run-frida-server

pip install -r requirements.txt

python3.10 -m pip install --upgrade pip

python3 frida-server.py

**Comment by newbit1** [comment]
> > 
> 
> you used these commands only correct?
> git clone https://github.com/6a6f6a6f/run-frida-server.git && cd run-frida-server
> 
> pip install -r requirements.txt
> 
> python3.10 -m pip install --upgrade pip
> 
> python3 frida-server.py


Yes, and no.
I didnt use the upgrade pip command.

**Comment by americanocb** [comment]
> > > 
> > 
> > 
> > você usou apenas esses comandos correto? 
> > git clone https://github.com/6a6f6a6f/run-frida-server.git && cd run-frida-server
> > pip install -r requisitos.txt
> > python3.10 -m pip install --upgrade pip
> > python3 frida-server.py
> 
> Sim e não. Eu não usei o comando pip de atualização.

I understood, so he used the same commands as me, but I don't understand why it's not going, I also didn't find any information 
![Captura de Tela 2023-06-28 às 13 55 14](https://github.com/newbit1/rootAVD/assets/135690169/342457f4-fe0c-43a0-857f-b7e5a435a711)
on the internet regarding this error, but it certainly has to do with the root magisk on avd android 10 that doesn't allow me privileges root.[](url)

**Comment by newbit1** [comment]
No I don't think so. These two effect are totally unrelated to each other.
I think your are mixing something up. Your su issue has nothing to do with
your python issue.

1st, if you use Magisk to gain root in your AVD, don't use commands like `adb root`,
`adb remount` and so on, just `su`. 
These commands are for non PlayStore AVDs, which can be rooted out of the box.
PlayStore AVDs can't be rooted officially, hence this script to install Magisk on it.
Magisk does all its Magic with mounting and overlaying partitions by its own.
Changes on the system partitions are made with modules, not with `adb remount`.
Only use `su` to gain root in a shell. This is what the python script is also doing.
```
run_adb_command('push ./frida-server /data/local/tmp')
run_adb_command('shell su -c "chmod +x /data/local/tmp/frida-server"')
run_adb_command('shell su -c "./data/local/tmp/frida-server -D"', True)
```
Which translates to manually typed in commands:
```
adb push ./frida-server /data/local/tmp
adb shell su -c "chmod +x /data/local/tmp/frida-server"
adb shell su -c "./data/local/tmp/frida-server -D"
```

2nd.
Your frida install issue is related to a type casting, which was deprecated between
Python 2 and Python 3. But it works on my machine with Python 3.10.8. So I guess
there was some kind of backwards compatibility fix along the way. Python is
bitch, and can sometimes driving you crazy. For me, I often purge HomeBrew
and all its Installations incl. Python and make a clean install.

The whole rootAVD script is running as a user, and it executes binarys without root.
Why don't you go into the same directory I am using?
```
adb shell
cd /data/data/com.android.shell
mkdir frida-server
exit
adb push frida-server /data/data/com.android.shell/frida-server/
adb shell
md5sum /data/data/com.android.shell/frida-server/frida-server
chmod +x /data/data/com.android.shell/frida-server/frida-server
ls -lah /data/data/com.android.shell/frida-server/
/data/data/com.android.shell/frida-server/frida-server -D
```
And if you really do need be root to run frida-server probably, just become root by su:
```
adb shell
su
md5sum /data/data/com.android.shell/frida-server/frida-server
chmod +x /data/data/com.android.shell/frida-server/frida-server
ls -lah /data/data/com.android.shell/frida-server/
./data/data/com.android.shell/frida-server/frida-server -D
```

**Comment by americanocb** [comment]
I updated my python
I used the commands
adb shell
su
md5sum /data/data/com.android.shell/frida-server/frida-server
chmod +x /data/data/com.android.shell/frida-server/frida-server
ls -lah /data/data/com.android.shell/frida-server/
./data/data/com.android.shell/frida-server/frida-server -D
I still don't have root privileges

**Comment by newbit1** [comment]
I am sorry.
Cant help you anymore.
