### ISSUE TITLE
Images not found (Android Emulator via Visual Studio 2022)

### ISSUE THREAD

**Issue by SeriousM** [newbit1/rootAVD#81]
Hi! I use android emulator installed by Visual Studio 2022.
Because of that, the android sdks are installed under `C:\Program Files (x86)\Android\android-sdk` instead of `%LOCALAPPDATA%\Android\Sdk`.

I tried to set the `ANDROID_HOME` to `C:\Program Files (x86)\Android` yet `rootADV.bat` didn't found any images.
The only thing that helped me is to create the folder `C:\Users\<USER>\AppData\Local\Android` and make a softlink by issuing as administrator `mklink /D "C:\Users\<USER>\AppData\Local\Android\Sdk" "C:\Program Files (x86)\Android\android-sdk"`.

From now on all the images were listed and I was able to root my emulated android via
```
rootAVD.bat
rootAVD.bat ListAllAVDs
rootAVD.bat system-images\android-33\google_apis_playstore\x86_64\ramdisk.img
```

This may be interesting to others so I added this issue.

Can be closed if you want.

**Comment by newbit1** [comment]
thanks!! i will have look into it. lets keep it open until its fixed.

**Comment by newbit1** [comment]
perhaps you just used the wrong path. in the aosp is stated:
ANDROID_HOME
Sets the path to the SDK installation directory. Once set, the value does not typically change and can be shared by multiple users on the same machine. ANDROID_SDK_ROOT, which also points to the SDK installation directory, is deprecated. If you continue to use it, Android Studio and the Android Gradle plugin will check that the old and new variables are consistent.

try to set it to:
C:\Program Files (x86)\Android\android-sdk

**Comment by SeriousM** [comment]
Hi @newbit1, thanks for the investigation. I tried to `set ANDROID_HOME=C:\Program Files (x86)\Android\android-sdk` but that resulted in an error because the path contains spaces (thanks windows...). Using `set ANDROID_HOME="C:\Program Files (x86)\Android\android-sdk"` (with quotes) doesn't help.

Anyway, my solution with the directory-softlink helped me and maybe others with the same issues may find that useful too.

**Comment by newbit1** [comment]
it is not the spaces. I implemented space handling this time... my bet is on the paranthesis...

**Comment by newbit1** [comment]
I was wrong and lost my bet.
It seems to be the handling for more than one space wasn't well written from me.
So you were absolutely right with:
> that resulted in an error because the path contains spaces

thank you for pointing this out to me, it should be fixed now.
Please try again and report back.

**Comment by SeriousM** [comment]
yes, you did it!
```
set ANDROID_HOME=C:\Program Files (x86)\Android
rootAVD.bat
```
works perfect, thank you!
