### ISSUE TITLE
please add the missing else keyword between ignoring echo and actual push

### ISSUE THREAD

**Issue by kautkadaskludas** [newbit1/rootAVD#89]
https://github.com/newbit1/rootAVD/blame/52ca070f7ca68734cf94cc7ade7c571633eb2d79/rootAVD.sh#L762

otherwise it results in error that Magisc.zip is not present on the device (because has not been pushed)

**Comment by newbit1** [comment]
I don't get it. What exactly is the issue here?
Please provide logs and more infos about your avd and magisk version.
