### ISSUE TITLE
The script doesn't check if it has permission to write.

### ISSUE THREAD

**Issue by mio-19** [newbit1/rootAVD#90]
I used this script to root Huawei MobileAppEngine, which is basically an modified AVD.

In powershell
```
$env:ANDROID_HOME = "C:\Program Files\MobileAppEngine\EmulatorSdk"
.\rootAVD.bat "system-images\android-28\default\x86_64\ramdisk.img"
```

When I ran it in normal powershell, the script completed successfully but no file was changed.
Then I ran it with admin priv, everything works perfectly.

**Comment by newbit1** [comment]
dont use PS, take cmd.
but this wont solve your admin rights issue.
